from __future__ import annotations
import asyncio, base64, csv, html, io, json, os, random, re, secrets, tempfile
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path
from urllib.parse import urlencode, urljoin, urlparse
from zoneinfo import ZoneInfo

import httpx
from bs4 import BeautifulSoup
from cryptography.fernet import Fernet
from ddgs import DDGS
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse, RedirectResponse, HTMLResponse
from itsdangerous import URLSafeTimedSerializer
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from sqlalchemy import create_engine, text

TOKEN=os.getenv("TELEGRAM_BOT_TOKEN","")
BASE=os.getenv("PUBLIC_BASE_URL","").rstrip("/")
WEBHOOK_SECRET=os.getenv("TELEGRAM_WEBHOOK_SECRET","")
DB=os.getenv("DATABASE_URL","sqlite:///./scoutbot.db")
APP_SECRET=os.getenv("APP_SECRET","change-me")
ENC_KEY=os.getenv("TOKEN_ENCRYPTION_KEY","")
GOOGLE_CLIENT_ID=os.getenv("GOOGLE_CLIENT_ID","")
GOOGLE_CLIENT_SECRET=os.getenv("GOOGLE_CLIENT_SECRET","")
GOOGLE_REDIRECT_URI=os.getenv("GOOGLE_REDIRECT_URI","") or (f"{BASE}/oauth/google/callback" if BASE else "")
MAX_FIND=int(os.getenv("MAX_FIND_COUNT","30"))
TIMEOUT=float(os.getenv("REQUEST_TIMEOUT","12"))
TZ=ZoneInfo(os.getenv("TIMEZONE_NAME","Africa/Lagos"))
YEAR=datetime.now(timezone.utc).year

if DB.startswith("postgres://"): DB="postgresql+psycopg://"+DB[len("postgres://"):]
elif DB.startswith("postgresql://"): DB="postgresql+psycopg://"+DB[len("postgresql://"):]

engine=create_engine(DB,pool_pre_ping=True,future=True)
serializer=URLSafeTimedSerializer(APP_SECRET,salt="author-scout")
try:
    fernet=Fernet(ENC_KEY.encode()) if ENC_KEY else None
except Exception:
    fernet=None
TG=f"https://api.telegram.org/bot{TOKEN}"
TGFILE=f"https://api.telegram.org/file/bot{TOKEN}"
EMAIL_RE=re.compile(r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}",re.I)
HEADERS={"User-Agent":"Mozilla/5.0 AuthorScoutTeamBot/2.0"}
SOCIAL={"facebook.com","instagram.com","x.com","twitter.com","linkedin.com","youtube.com","tiktok.com","goodreads.com","amazon.com","wikipedia.org"}
GMAIL_SCOPE="openid email https://www.googleapis.com/auth/gmail.send"
GOOGLE_AUTH="https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN="https://oauth2.googleapis.com/token"
GOOGLE_USERINFO="https://openidconnect.googleapis.com/v1/userinfo"
GMAIL_SEND="https://gmail.googleapis.com/gmail/v1/users/me/messages/send"

app=FastAPI(title="Author Scout Team Bot",version="2.0")

def now(): return datetime.now(timezone.utc)
def iso(dt=None): return (dt or now()).isoformat()
def esc(v): return html.escape(str(v or ""))
def rows(q,**p):
    with engine.begin() as c: return [dict(r._mapping) for r in c.execute(text(q),p)]
def row(q,**p):
    x=rows(q,**p); return x[0] if x else None
def execq(q,**p):
    with engine.begin() as c: c.execute(text(q),p)

def init_db():
    pk="INTEGER PRIMARY KEY AUTOINCREMENT" if DB.startswith("sqlite") else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    stmts=[
      "CREATE TABLE IF NOT EXISTS users(telegram_user_id BIGINT PRIMARY KEY,username TEXT DEFAULT '',first_name TEXT DEFAULT '',team_id INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS teams(id {pk},name TEXT NOT NULL,invite_code TEXT NOT NULL UNIQUE,owner_user_id BIGINT NOT NULL,created_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS prospects(id {pk},normalized_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,country TEXT DEFAULT '',genre TEXT DEFAULT '',website TEXT DEFAULT '',email TEXT DEFAULT '',email_source_url TEXT DEFAULT '',verification_status TEXT DEFAULT 'unverified',bio TEXT DEFAULT '',books TEXT DEFAULT '',recent_activity TEXT DEFAULT '',source_urls TEXT DEFAULT '[]',discovery_platform TEXT DEFAULT '',discovery_source_type TEXT DEFAULT '',discovery_source_url TEXT DEFAULT '',discovery_query TEXT DEFAULT '',discovery_evidence TEXT DEFAULT '',discovery_confidence INTEGER DEFAULT 0,claimed_team_id INTEGER NOT NULL,claimed_by_user_id BIGINT NOT NULL,claimed_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS messages(id {pk},team_id INTEGER NOT NULL,prospect_id INTEGER NOT NULL,imported_by_user_id BIGINT NOT NULL,subject TEXT DEFAULT '',body TEXT DEFAULT '',status TEXT DEFAULT 'ready',sender_email TEXT DEFAULT '',sent_by_user_id BIGINT,sent_at TEXT DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS sender_emails(id {pk},telegram_user_id BIGINT NOT NULL,email TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(telegram_user_id,email))",
      f"CREATE TABLE IF NOT EXISTS scout_events(id {pk},telegram_user_id BIGINT NOT NULL,team_id INTEGER NOT NULL,prospect_id INTEGER NOT NULL,created_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS gmail_accounts(id {pk},telegram_user_id BIGINT NOT NULL,google_subject TEXT NOT NULL,email TEXT NOT NULL,refresh_token_enc TEXT NOT NULL,test_opt_in INTEGER NOT NULL DEFAULT 0,test_scope TEXT NOT NULL DEFAULT 'team',connected_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(telegram_user_id,google_subject))",
      f"CREATE TABLE IF NOT EXISTS delivery_tests(id {pk},team_id INTEGER NOT NULL,requested_by_user_id BIGINT NOT NULL,message_id INTEGER NOT NULL,sender_gmail_id INTEGER NOT NULL,sender_email TEXT NOT NULL,requested_count INTEGER NOT NULL DEFAULT 10,sent_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'sending',created_at TEXT NOT NULL,completed_at TEXT DEFAULT '')",
      f"CREATE TABLE IF NOT EXISTS delivery_test_recipients(id {pk},test_id INTEGER NOT NULL,gmail_account_id INTEGER NOT NULL,owner_user_id BIGINT NOT NULL,email TEXT NOT NULL,result TEXT NOT NULL DEFAULT 'pending',sent_at TEXT NOT NULL,responded_at TEXT DEFAULT '',UNIQUE(test_id,gmail_account_id))",
      f"CREATE TABLE IF NOT EXISTS search_runs(id {pk},team_id INTEGER NOT NULL,telegram_user_id BIGINT NOT NULL,request_text TEXT DEFAULT '',parsed_spec TEXT DEFAULT '{{}}',search_routes TEXT DEFAULT '[]',raw_results INTEGER DEFAULT 0,candidates INTEGER DEFAULT 0,checked INTEGER DEFAULT 0,accepted INTEGER DEFAULT 0,duplicates INTEGER DEFAULT 0,created_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS user_states(telegram_user_id BIGINT PRIMARY KEY,state TEXT NOT NULL DEFAULT '',payload TEXT DEFAULT '{}',updated_at TEXT NOT NULL)"
    ]
    with engine.begin() as c:
        for s in stmts: c.execute(text(s))
    # Backward-compatible columns for existing databases.
    for alter in [
        "ALTER TABLE messages ADD COLUMN recipient_email TEXT DEFAULT ''",
        "ALTER TABLE messages ADD COLUMN body_english TEXT DEFAULT ''",
        "ALTER TABLE messages ADD COLUMN reply_status TEXT DEFAULT ''",
        "ALTER TABLE messages ADD COLUMN replied_at TEXT DEFAULT ''",
        "ALTER TABLE messages ADD COLUMN reply_notes TEXT DEFAULT ''",
        "ALTER TABLE messages ADD COLUMN sent_via TEXT DEFAULT ''",
        "ALTER TABLE messages ADD COLUMN auto_sent INTEGER DEFAULT 0",
        "ALTER TABLE prospects ADD COLUMN discovery_platform TEXT DEFAULT ''",
        "ALTER TABLE prospects ADD COLUMN discovery_source_type TEXT DEFAULT ''",
        "ALTER TABLE prospects ADD COLUMN discovery_source_url TEXT DEFAULT ''",
        "ALTER TABLE prospects ADD COLUMN discovery_query TEXT DEFAULT ''",
        "ALTER TABLE prospects ADD COLUMN discovery_evidence TEXT DEFAULT ''",
        "ALTER TABLE prospects ADD COLUMN discovery_confidence INTEGER DEFAULT 0"
    ]:
        try:
            with engine.begin() as c:
                c.execute(text(alter))
        except Exception:
            pass

def ensure_user(u):
    uid=int(u["id"]); ex=row("SELECT telegram_user_id FROM users WHERE telegram_user_id=:u",u=uid)
    if not ex: execq("INSERT INTO users(telegram_user_id,username,first_name,created_at,updated_at) VALUES(:u,:n,:f,:t,:t)",u=uid,n=u.get("username",""),f=u.get("first_name",""),t=iso())
    else: execq("UPDATE users SET username=:n,first_name=:f,updated_at=:t WHERE telegram_user_id=:u",u=uid,n=u.get("username",""),f=u.get("first_name",""),t=iso())
    return uid

def team(uid):
    return row("SELECT t.* FROM users u JOIN teams t ON t.id=u.team_id WHERE u.telegram_user_id=:u",u=uid)

def get_user_state(uid):
    return row("SELECT * FROM user_states WHERE telegram_user_id=:u",u=uid)

def set_user_state(uid,state,payload=None):
    t=iso(); p=json.dumps(payload or {})
    execq("""INSERT INTO user_states(telegram_user_id,state,payload,updated_at)
        VALUES(:u,:s,:p,:d)
        ON CONFLICT(telegram_user_id) DO UPDATE SET state=:s,payload=:p,updated_at=:d""",
        u=uid,s=state,p=p,d=t)

def clear_user_state(uid):
    execq("DELETE FROM user_states WHERE telegram_user_id=:u",u=uid)


def invite():
    alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    for _ in range(50):
        c="".join(secrets.choice(alphabet) for _ in range(7))
        if not row("SELECT id FROM teams WHERE invite_code=:c",c=c): return c
    raise RuntimeError("Could not create code")

def pkey(d):
    if d.get("email"): return "email:"+d["email"].lower().strip()
    if d.get("website"):
        try:
            p=urlparse(d["website"] if "://" in d["website"] else "https://"+d["website"])
            return "site:"+p.netloc.lower().replace("www.","")+p.path.rstrip("/")
        except: pass
    return "name:"+re.sub("[^a-z0-9]","",(d.get("name") or "").lower())+":"+re.sub("[^a-z0-9]","",(d.get("country") or "").lower())

def claim(uid,tid,d):
    k=pkey(d)
    email=(d.get("email") or "").lower().strip()
    website=(d.get("website") or "").strip().lower().rstrip("/")
    name=(d.get("name") or "").strip()
    country=(d.get("country") or "").strip()
    ex=row("""SELECT * FROM prospects WHERE normalized_key=:k
        OR (:e<>'' AND lower(email)=:e)
        OR (:w<>'' AND lower(rtrim(website,'/'))=:w)
        OR (:n<>'' AND :c<>'' AND lower(name)=lower(:n) AND lower(country)=lower(:c))
        LIMIT 1""",k=k,e=email,w=website,n=name,c=country)
    if ex:return ex["id"],False,ex
    source_url=(d.get("discovery_source_url") or "").strip()
    source_platform=(d.get("discovery_platform") or host(source_url) or "").strip()
    source_type=(d.get("discovery_source_type") or "").strip()
    vals={"k":k,"n":name,"c":country,"g":d.get("genre",""),"w":d.get("website",""),"e":email,"es":d.get("email_source_url",""),"v":d.get("verification_status","unverified"),"b":d.get("bio",""),"bk":d.get("books",""),"a":d.get("recent_activity",""),"s":json.dumps(d.get("source_urls",[])),"dp":source_platform,"dst":source_type,"dsu":source_url,"dq":(d.get("discovery_query") or "")[:1200],"de":(d.get("discovery_evidence") or "")[:1600],"dc":max(0,min(100,int(d.get("discovery_confidence") or 0))),"tid":tid,"uid":uid,"t":iso()}
    try:
        with engine.begin() as c:
            r=c.execute(text("INSERT INTO prospects(normalized_key,name,country,genre,website,email,email_source_url,verification_status,bio,books,recent_activity,source_urls,discovery_platform,discovery_source_type,discovery_source_url,discovery_query,discovery_evidence,discovery_confidence,claimed_team_id,claimed_by_user_id,claimed_at,updated_at) VALUES(:k,:n,:c,:g,:w,:e,:es,:v,:b,:bk,:a,:s,:dp,:dst,:dsu,:dq,:de,:dc,:tid,:uid,:t,:t) RETURNING id"),vals)
            pid=int(r.scalar_one())
            c.execute(text("INSERT INTO scout_events(telegram_user_id,team_id,prospect_id,created_at) VALUES(:uid,:tid,:pid,:t)"),{"uid":uid,"tid":tid,"pid":pid,"t":vals["t"]})
        return pid,True,None
    except Exception:
        ex=row("""SELECT * FROM prospects WHERE normalized_key=:k
          OR (:e<>'' AND lower(email)=:e)
          OR (:w<>'' AND lower(rtrim(website,'/'))=:w)
          LIMIT 1""",k=k,e=email,w=website)
        return (ex["id"],False,ex) if ex else (0,False,None)

async def tg(method,data=None,files=None):
    async with httpx.AsyncClient(timeout=60) as c:
        r=await c.post(f"{TG}/{method}",data=data,files=files); r.raise_for_status(); j=r.json()
        if not j.get("ok"): raise RuntimeError(j)
        return j.get("result")
def _telegram_text(msg):
    s=str(msg or "")
    return s.replace("\\n","\n")

async def send(chat,msg,kb=None):
    msg=_telegram_text(msg)
    d={"chat_id":str(chat),"text":msg,"parse_mode":"HTML","disable_web_page_preview":"true"}
    if kb: d["reply_markup"]=json.dumps(kb)
    return await tg("sendMessage",d)

async def edit_msg(chat,message_id,msg,kb=None):
    msg=_telegram_text(msg)
    d={"chat_id":str(chat),"message_id":str(message_id),"text":msg,"parse_mode":"HTML","disable_web_page_preview":"true"}
    if kb: d["reply_markup"]=json.dumps(kb)
    try:
        return await tg("editMessageText",d)
    except Exception:
        return None

async def send_doc(chat,path,cap=""):
    with open(path,"rb") as f: return await tg("sendDocument",{"chat_id":str(chat),"caption":cap},{"document":(Path(path).name,f)})

def ddgs(q,n=10):
    out=[]; seen=set()
    backends=["bing","duckduckgo","brave","yahoo"]
    try:
        with DDGS(timeout=max(5,int(TIMEOUT))) as d:
            for backend in backends:
                if len(out)>=n: break
                try:
                    results=d.text(q,max_results=n,safesearch="moderate",backend=backend)
                    got=0
                    for x in results:
                        u=x.get("href") or x.get("url","")
                        if not u or u in seen: continue
                        seen.add(u); got+=1
                        out.append({"title":x.get("title",""),"url":u,"snippet":x.get("body") or x.get("snippet","")})
                        if len(out)>=n: break
                    print(f"SEARCH_BACKEND backend={backend} count={got}")
                except Exception as e:
                    print(f"SEARCH_BACKEND_ERROR backend={backend} {type(e).__name__}: {e}")
    except Exception as e:
        print(f"SEARCH_ERROR {type(e).__name__}: {e}")
    print(f"SEARCH_RESULT count={len(out)} query={q[:140]}")
    return out
async def search(q,n=10): return await asyncio.to_thread(ddgs,q,n)

def cand(title,snip=""):
    t=re.sub(r"\b(official site|official website|author|writer|books|home)\b","",title,flags=re.I)
    for sep in [" | "," – "," — "," - ",": "]:
        if sep in t: t=t.split(sep)[0]
    t=re.sub(r"\s+"," ",t).strip(" -|:,.")
    if 2<=len(t.split())<=5 and len(t)<80:return t
    m=re.search(r"\b([A-Z][a-zÀ-ÿ'’-]+(?:\s+[A-Z][a-zÀ-ÿ'’-]+){1,3})\b",snip); return m.group(1) if m else ""

def host(u):
    try:return urlparse(u).netloc.lower().replace("www.","")
    except:return ""
def official(u,n):
    h=host(u)
    if not h or any(h==s or h.endswith("."+s) for s in SOCIAL):return False
    compact=re.sub("[^a-z]","",h)
    return any(re.sub("[^a-z]","",x.lower()) in compact for x in n.split() if len(x)>2)
async def fetch(u):
    try:
        async with httpx.AsyncClient(timeout=TIMEOUT,headers=HEADERS,follow_redirects=True) as c:
            r=await c.get(u)
            if r.status_code>=400 or "text/html" not in r.headers.get("content-type",""):return "",u
            return r.text[:1000000],str(r.url)
    except:return "",u
def emails(raw):
    s=BeautifulSoup(raw,"html.parser"); vals=EMAIL_RE.findall(s.get_text(" "))
    for a in s.select('a[href^="mailto:"]'): vals+=EMAIL_RE.findall(a.get("href",""))
    bad={"support","sales","admin","privacy","legal","noreply","no-reply"}; out=[]
    for e in vals:
        e=e.lower().strip(".,;:()[]<>")
        if e.split("@")[0] not in bad and e not in out: out.append(e)
    return out

async def research(name,country="",genre="",hint=""):
    rs=await search(f'"{name}" author official website',8)
    if hint:rs=[{"title":"hint","url":hint,"snippet":""}]+rs
    website=next((r["url"] for r in rs if official(r["url"],name)), "")
    if not website: website=next((r["url"] for r in rs if r["url"] and not any(x in host(r["url"]) for x in ["amazon.","goodreads.","wikipedia."])), "")
    bio=emailv=source=""; sources=[]; verified="unverified"
    if website:
        raw,final=await fetch(website); sources.append(final); s=BeautifulSoup(raw,"html.parser")
        bio=re.sub(r"\s+"," ",s.get_text(" ")).strip()[:700]; em=emails(raw)
        if em: emailv=em[0]; source=final; verified="verified_public"
        if not emailv:
            for a in s.find_all("a",href=True):
                label=(a.get_text(" ")+" "+a["href"]).lower()
                if "contact" in label:
                    u=urljoin(final,a["href"])
                    if host(u)==host(final):
                        rr,ff=await fetch(u); em=emails(rr); sources.append(ff)
                        if em: emailv=em[0]; source=ff; verified="verified_public"; break
    act=await search(f'"{name}" author {YEAR} book OR event OR release',3)
    activity=(act[0]["title"]+": "+act[0]["snippet"])[:700] if act else ""
    if act and act[0]["url"]:sources.append(act[0]["url"])
    return {"name":name,"country":country,"genre":genre,"website":website,"email":emailv,"email_source_url":source,"verification_status":verified,"bio":bio,"books":"","recent_activity":activity,"source_urls":list(dict.fromkeys(sources))}

def _yes(v,default=True):
    if v is None:return default
    return str(v).strip().lower() not in {"0","no","false","off","optional","none","noemail"}

def find_query_is_specific(spec):
    if any((spec.get(k) or "").strip() for k in ("name","country","genre","language")):
        return True
    q=(spec.get("query") or "").strip().lower()
    if not q:return False
    generic={"author","authors","writer","writers","book","books","novelist","novelists","find","search","scout","people"}
    toks=[x for x in re.findall(r"[a-z0-9À-ÿ'’-]+",q) if x not in generic]
    return bool(toks)

def parse_find(a):
    raw=(a or "").strip()
    spec={
        "count":10,"country":"","genre":"","gender":"any","name":"",
        "language":"","year":"","query":"","require_email":True,
        "require_website":True,"raw":raw
    }
    if not raw:
        return spec

    # Explicit key=value or key:value filters can appear in any order.
    keymap={
        "count":"count","n":"count","country":"country","location":"country",
        "genre":"genre","gender":"gender","sex":"gender","name":"name",
        "author":"name","language":"language","lang":"language","year":"year",
        "email":"email","website":"website","site":"website","query":"query","q":"query"
    }
    explicit_spans=[]
    pattern=re.compile(r'(?i)\\b(count|n|country|location|genre|gender|sex|name|author|language|lang|year|email|website|site|query|q)\\s*[:=]\\s*("[^"]+"|\'[^\']+\'|[^|,;]+)')
    for m in pattern.finditer(raw):
        k=keymap[m.group(1).lower()]
        v=m.group(2).strip().strip('"\' ').strip()
        explicit_spans.append(m.span())
        if k=="count":
            try:spec["count"]=min(max(int(v),1),MAX_FIND)
            except:pass
        elif k=="email":
            spec["require_email"]=_yes(v,True)
        elif k=="website":
            spec["require_website"]=_yes(v,True)
        elif k=="gender":
            spec["gender"]=v.lower()
        else:
            spec[k]=v

    # Remove explicit filters from the free-text intent.
    cleaned=raw
    for s,e in reversed(explicit_spans):
        cleaned=cleaned[:s]+" "+cleaned[e:]
    cleaned=re.sub(r'\\s+',' ',cleaned).strip(" |,;")

    # Backward-compatible pipe format:
    # /find 5 | Saudi Arabia | Karim | male | email
    parts=[x.strip() for x in raw.split("|") if x.strip()]
    positional=not explicit_spans and len(parts)>1
    if positional:
        try:
            spec["count"]=min(max(int(parts[0]),1),MAX_FIND); parts=parts[1:]
        except:pass
        if parts:
            spec["country"]=parts[0]
        if len(parts)>1:
            spec["query"]=parts[1]
        for x in parts[2:]:
            xl=x.lower()
            if xl in {"male","female","any"}:
                spec["gender"]=xl
            elif xl in {"email","email required","verified email"}:
                spec["require_email"]=True
            elif xl in {"optional","noemail","no email","email optional"}:
                spec["require_email"]=False
            elif xl in {"website","site","website required"}:
                spec["require_website"]=True
            elif xl in {"no website","website optional"}:
                spec["require_website"]=False
            else:
                spec["query"]=(spec["query"]+" "+x).strip()
    else:
        # Leading number is treated as requested count.
        m=re.match(r'^\\s*(\\d{1,2})\\s+(.*)$',cleaned)
        if m:
            spec["count"]=min(max(int(m.group(1)),1),MAX_FIND)
            cleaned=m.group(2).strip()
        if cleaned and not spec["query"]:
            spec["query"]=cleaned

    # Natural-language convenience: "Karim in Saudi Arabia" or "authors named Karim in Saudi Arabia".
    q=spec["query"] or cleaned
    m=re.search(r'(?i)\\b(?:authors?|writers?)\\s+(?:named|called)\\s+([A-Za-zÀ-ÿ\'’-]+)(?:\\s+in\\s+(.+))?$',q)
    if m:
        if not spec["name"]:spec["name"]=m.group(1).strip()
        if m.group(2) and not spec["country"]:spec["country"]=m.group(2).strip()
    else:
        m=re.match(r"(?i)^([A-Za-zÀ-ÿ'’-]{2,30})\\s+in\\s+(.{2,60})$",q.strip())
        if m and not any(w in m.group(1).lower() for w in {"author","writer","book"}):
            if not spec["name"]:spec["name"]=m.group(1).strip()
            if not spec["country"]:spec["country"]=m.group(2).strip()

    return spec

async def find_authors(spec,progress=None):
    count=spec["count"]
    country=spec.get("country","")
    genre=spec.get("genre","")
    gender=spec.get("gender","any")
    name_filter=spec.get("name","")
    language=spec.get("language","")
    year=spec.get("year","")
    free_query=spec.get("query","")
    require_email=spec.get("require_email",True)
    require_website=spec.get("require_website",True)

    aliases={"uae":"United Arab Emirates","uk":"United Kingdom","usa":"United States","us":"United States","ksa":"Saudi Arabia","saudi":"Saudi Arabia"}
    country_term=aliases.get((country or "").strip().lower(),country)

    intent_parts=[]
    if name_filter:intent_parts.append(f'"{name_filter}"')
    if free_query:intent_parts.append(free_query)
    if country_term:intent_parts.append(country_term)
    if genre:intent_parts.append(genre)
    if language:intent_parts.append(language)
    if gender in {"male","female"}:intent_parts.append(gender)
    base=" ".join(dict.fromkeys([x.strip() for x in intent_parts if x.strip()])).strip() or "author"

    activity_year=year or str(YEAR)
    queries=[
        f'{base} author official website contact email',
        f'{base} writer novelist books official site',
        f'{base} author {activity_year} release event newsletter'
    ]

    seen=set();cands=[];raw_results=0
    for qi,q in enumerate(queries,1):
        if progress:
            await progress(
                f"🔎 <b>Search pass {qi}/3</b>\\n"
                f"Query: {esc(base)}\\n\\n"
                f"Candidates collected: <b>{len(cands)}</b>"
            )
        rs=await search(q,max(15,count*3))
        raw_results+=len(rs)
        print(f"FIND_PROGRESS pass={qi} raw_results={len(rs)} query={q[:180]}")
        for r in rs:
            n=cand(r["title"],r["snippet"])
            if not n:continue
            if name_filter:
                wanted=[x.lower() for x in re.findall(r"[A-Za-zÀ-ÿ'’-]+",name_filter)]
                nl=n.lower()
                if wanted and not all(x in nl for x in wanted):
                    continue
            k=re.sub("[^a-z0-9]","",n.lower())
            if k and k not in seen:
                seen.add(k);cands.append((n,r["url"]))

    if progress:
        await progress(
            f"📋 <b>{len(cands)} candidate names found</b>\\n"
            f"Now checking official websites and public contact details…\\n\\n"
            f"Raw search results checked: <b>{raw_results}</b>"
        )

    out=[];checked=0;with_email=0;with_website=0
    max_check=min(len(cands),max(count*6,30))
    for n,h in cands[:max_check]:
        checked+=1
        if progress and (checked==1 or checked%2==0):
            await progress(
                f"🔬 <b>Verification in progress</b>\\n"
                f"Candidate {checked}/{max_check}: {esc(n)}\\n"
                f"Accepted so far: <b>{len(out)}</b>\\n"
                f"Websites found: <b>{with_website}</b>\\n"
                f"Public emails found: <b>{with_email}</b>"
            )
        d=await research(n,country_term,genre,h)
        if d.get("website"):with_website+=1
        if d.get("email"):with_email+=1
        if require_website and not d.get("website"):continue
        if require_email and not d.get("email"):continue
        out.append(d)
        if len(out)>=count:break

    print(f"FIND_DONE raw_results={raw_results} candidates={len(cands)} checked={checked} websites={with_website} with_email={with_email} accepted={len(out)} query={base[:180]}")
    return out,{
        "raw_results":raw_results,"candidates":len(cands),"checked":checked,
        "with_email":with_email,"with_website":with_website,"query":base,"queries":queries
    }

def enc(v):
    if not fernet:raise RuntimeError("TOKEN_ENCRYPTION_KEY missing")
    return fernet.encrypt(v.encode()).decode()
def dec(v):
    if not fernet:raise RuntimeError("TOKEN_ENCRYPTION_KEY missing")
    return fernet.decrypt(v.encode()).decode()
def gmail_ok():return all([GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI,BASE,ENC_KEY])
async def access(refresh):
    async with httpx.AsyncClient(timeout=30) as c:
        r=await c.post(GOOGLE_TOKEN,data={"client_id":GOOGLE_CLIENT_ID,"client_secret":GOOGLE_CLIENT_SECRET,"refresh_token":refresh,"grant_type":"refresh_token"});r.raise_for_status();return r.json()["access_token"]
async def gmail_send(account,to,subject,body):
    token=await access(dec(account["refresh_token_enc"])); m=EmailMessage();m["To"]=to;m["From"]=account["email"];m["Subject"]=subject;m.set_content(body)
    raw=base64.urlsafe_b64encode(m.as_bytes()).decode().rstrip("=")
    async with httpx.AsyncClient(timeout=30) as c:
        r=await c.post(GMAIL_SEND,headers={"Authorization":f"Bearer {token}"},json={"raw":raw});r.raise_for_status();return r.json()


def norm_header(v):
    return re.sub(r"[^a-z0-9]+"," ",str(v or "").lower()).strip()

def prompt_text():
    p=Path(__file__).with_name("AUTHOR_RESEARCH_PROMPT_V3_2.txt")
    try:return p.read_text(encoding="utf-8")
    except:return "Use the supplied author rows as research seeds. Verify every important fact, preserve Source Row ID and Canonical Author ID, and return an XLSX with Selected Subject and Best First Message — Author Language."

def style_sheet(ws, widths=None):
    fill=PatternFill("solid",fgColor="1F4E78")
    for cell in ws[1]:
        cell.font=Font(bold=True,color="FFFFFF")
        cell.fill=fill
        cell.alignment=Alignment(horizontal="center",vertical="center",wrap_text=True)
    ws.freeze_panes="A2"
    ws.auto_filter.ref=ws.dimensions
    ws.sheet_view.showGridLines=False
    if widths:
        for col,w in widths.items():ws.column_dimensions[col].width=w
    for row in ws.iter_rows(min_row=2):
        for cell in row:cell.alignment=Alignment(vertical="top",wrap_text=True)

async def export_chatgpt(chat,uid):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    ps=rows("SELECT * FROM prospects WHERE claimed_team_id=:t ORDER BY id",t=t["id"])
    if not ps:return await send(chat,"No authors to export yet. Scout authors first.")
    wb=Workbook(); ws=wb.active; ws.title="Authors & Messages"
    seed_headers=[
        "Source Row ID","Canonical Author ID","Author Name — Bot","Country — Bot","Genre — Bot",
        "Official Website — Bot","Public Professional Email — Bot","Email Source URL — Bot",
        "Email Verification Status — Bot","Bio / Research Seed — Bot","Books — Bot",
        "Recent Activity — Bot","Source URLs — Bot","Claimed At — Bot"
    ]
    enriched=[
        "Processing Status","Duplicate Of","Author Name — Verified","Country — Verified",
        "Primary Language","Genre","Official Website","Public Professional Email","Contact Type",
        "Email Source URL","Identity Confidence","Current Project","Current Project Stage",
        "Recent Activity / Current Moment","Why Now","Publisher","Literary Agent / Representation",
        "Foreign Rights Handler","Translation Status","Audio Status","Film / TV / Stage Status",
        "Publicity / Marketing Handler","Already-Solved Summary","Critical Unknowns",
        "Top Opportunity #1","Opportunity #1 Score","Opportunity #1 Evidence",
        "Top Opportunity #2","Opportunity #2 Score","Opportunity #2 Evidence",
        "Top Opportunity #3","Opportunity #3 Score","Opportunity #3 Evidence",
        "Top Opportunity #4","Opportunity #4 Score","Opportunity #4 Evidence",
        "Top Opportunity #5","Opportunity #5 Score","Opportunity #5 Evidence",
        "Primary Pivotal Unknown","Winning Pivotal Question","Message Current Anchor",
        "Message Distinctive Detail","Message Public-Information Boundary",
        "Subject Option 1","Subject Option 2","Subject Option 3","Selected Subject",
        "Best First Message — Author Language","Best First Message — English",
        "Expected Response Path 1","Expected Response Path 2","Expected Response Path 3",
        "Next Conversation State","Research Confidence","Research Notes",
        "Primary Source URL","Additional Source URLs","Research Date"
    ]
    ws.append(seed_headers+enriched)
    for p in ps:
        try:srcs=" | ".join(json.loads(p.get("source_urls") or "[]"))
        except:srcs=p.get("source_urls") or ""
        ws.append([
            f"AS-{p['id']}",f"AS-{p['id']}",p["name"],p["country"],p["genre"],p["website"],p["email"],
            p["email_source_url"],p["verification_status"],p["bio"],p["books"],p["recent_activity"],srcs,p["claimed_at"]
        ]+[""]*len(enriched))
    style_sheet(ws)
    for i,h in enumerate(seed_headers+enriched,1):
        letter=get_column_letter(i)
        ws.column_dimensions[letter].width=18
        if any(x in h.lower() for x in ["message","notes","evidence","activity","unknown","source urls","summary","bio"]):
            ws.column_dimensions[letter].width=38
        if "url" in h.lower() or "website" in h.lower():ws.column_dimensions[letter].width=32

    ins=wb.create_sheet("HOW TO USE")
    ins_rows=[
        ["AUTHOR SCOUT → CHATGPT → TELEGRAM WORKFLOW"],
        ["1","Upload this entire XLSX to ChatGPT. Do not copy authors one by one."],
        ["2","Tell ChatGPT: Read the 'ChatGPT Prompt' sheet and process every row in 'Authors & Messages' using that prompt."],
        ["3","ChatGPT must preserve Source Row ID, Canonical Author ID, and every original Bot column."],
        ["4","ChatGPT should independently verify important facts. Bot data is a research seed, not final proof."],
        ["5","ChatGPT should return a NEW XLSX using the columns already present in 'Authors & Messages' and may add the supporting Top Five Opportunities, Sources, and Run Log sheets required by the prompt."],
        ["6","For rows ready for outreach, the returned workbook should contain: Processing Status, Public Professional Email, Selected Subject, Best First Message — Author Language, and Best First Message — English."],
        ["7","Upload ChatGPT's returned XLSX directly back to this Telegram bot. The bot matches rows by Canonical Author ID / Source Row ID first, then email/name as fallback."],
        ["8","Use /queue for manual sending. Gmail-connected users can use the automatic send button."],
        ["9","Use /campaign or /stats for total authors, ready messages, sent messages and replies."],
        ["IMPORTANT","Do not remove or change AS- IDs. They allow the bot to match researched rows even if ChatGPT corrects the author's name or email."]
    ]
    for r in ins_rows:ins.append(r)
    ins["A1"].font=Font(bold=True,size=16,color="FFFFFF");ins["A1"].fill=PatternFill("solid",fgColor="1F4E78")
    ins.column_dimensions["A"].width=18;ins.column_dimensions["B"].width=110
    for row in ins.iter_rows():
        for cell in row:cell.alignment=Alignment(vertical="top",wrap_text=True)

    prs=wb.create_sheet("ChatGPT Prompt")
    prs.append(["Master Author Research & Messaging System v3.2"])
    prs["A1"].font=Font(bold=True,size=14,color="FFFFFF");prs["A1"].fill=PatternFill("solid",fgColor="1F4E78")
    for line in prompt_text().splitlines():prs.append([line])
    prs.column_dimensions["A"].width=120
    for row in prs.iter_rows():
        row[0].alignment=Alignment(vertical="top",wrap_text=True)

    tmp=tempfile.NamedTemporaryFile(suffix=".xlsx",delete=False);tmp.close()
    wb.save(tmp.name)
    try:await send_doc(chat,tmp.name,f"📥 {len(ps)} authors ready for ChatGPT research. Upload this same workbook to ChatGPT, then upload ChatGPT's returned XLSX back here.")
    finally:
        try:os.unlink(tmp.name)
        except:pass

async def send_brief(chat,uid):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    txt=(
        "AUTHOR SCOUT WORKFLOW\\n\\n"
        "1. Scout authors in Telegram.\\n"
        "2. Use /export to download the ChatGPT-ready XLSX.\\n"
        "3. Upload that XLSX to ChatGPT and instruct it to follow the embedded 'ChatGPT Prompt' sheet.\\n"
        "4. ChatGPT deep-researches each author, preserves AS- IDs, selects the best subject and first message, and returns an XLSX.\\n"
        "5. Upload the returned XLSX directly to this bot.\\n"
        "6. Use /queue to send manually, or connect Gmail for automatic sending.\\n"
        "7. Use /campaign to track total authors, ready, sent and replied.\\n\\n"
        "Required return fields for ready messages: Canonical Author ID or Source Row ID, Public Professional Email, Selected Subject, Best First Message — Author Language."
    )
    fd=tempfile.NamedTemporaryFile(mode="w",suffix=".txt",delete=False,encoding="utf-8")
    fd.write(txt);fd.close()
    try:await send_doc(chat,fd.name,"Author Scout workflow brief")
    finally:
        try:os.unlink(fd.name)
        except:pass

def campaign_counts(tid,start=None,end=None):
    total=int((row("SELECT COUNT(*) c FROM prospects WHERE claimed_team_id=:t",t=tid) or {"c":0})["c"])
    ready=int((row("SELECT COUNT(*) c FROM messages WHERE team_id=:t AND status='ready'",t=tid) or {"c":0})["c"])
    imported=int((row("SELECT COUNT(*) c FROM messages WHERE team_id=:t",t=tid) or {"c":0})["c"])
    if start and end:
        sent=int((row("SELECT COUNT(*) c FROM messages WHERE team_id=:t AND sent_at<>'' AND sent_at>=:s AND sent_at<:e",t=tid,s=iso(start),e=iso(end)) or {"c":0})["c"])
        replied=int((row("SELECT COUNT(*) c FROM messages WHERE team_id=:t AND replied_at<>'' AND replied_at>=:s AND replied_at<:e",t=tid,s=iso(start),e=iso(end)) or {"c":0})["c"])
    else:
        sent=int((row("SELECT COUNT(*) c FROM messages WHERE team_id=:t AND sent_at<>''",t=tid) or {"c":0})["c"])
        replied=int((row("SELECT COUNT(*) c FROM messages WHERE team_id=:t AND replied_at<>''",t=tid) or {"c":0})["c"])
    return {"authors":total,"imported":imported,"ready":ready,"sent":sent,"replied":replied}

async def campaign(chat,uid,arg=""):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    start=end=None;label="All time"
    if arg:
        p=arg.split()
        if len(p)==2:
            try:
                start=datetime.strptime(p[0],"%Y-%m-%d").replace(tzinfo=TZ).astimezone(timezone.utc)
                end=datetime.strptime(p[1],"%Y-%m-%d").replace(tzinfo=TZ).astimezone(timezone.utc)+timedelta(days=1)
                label=f"{p[0]} to {p[1]}"
            except:return await send(chat,"Use /campaign YYYY-MM-DD YYYY-MM-DD")
    x=campaign_counts(t["id"],start,end)
    rate=(x["replied"]/x["sent"]*100) if x["sent"] else 0
    await send(chat,
        f"<b>📊 {esc(t['name'])} campaign</b>\\n"
        f"Period: {esc(label)}\\n\\n"
        f"Authors scouted: <b>{x['authors']}</b>\\n"
        f"Messages imported: <b>{x['imported']}</b>\\n"
        f"Ready to send: <b>{x['ready']}</b>\\n"
        f"Sent: <b>{x['sent']}</b>\\n"
        f"Replies marked: <b>{x['replied']}</b>\\n"
        f"Reply rate: <b>{rate:.1f}%</b>"
    )

async def replies_view(chat,uid):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    rs=rows("""SELECT m.id,m.sent_at,COALESCE(NULLIF(m.recipient_email,''),p.email) email,p.name
        FROM messages m JOIN prospects p ON p.id=m.prospect_id
        WHERE m.team_id=:t AND m.status='sent' AND COALESCE(m.reply_status,'')=''
        ORDER BY m.sent_at DESC LIMIT 10""",t=t["id"])
    if not rs:return await send(chat,"No sent messages waiting to be marked as replied.")
    kb={"inline_keyboard":[[{"text":f"📬 {r['name'][:30]}","callback_data":f"replied:{r['id']}"}] for r in rs]}
    return await send(chat,"<b>Mark an author as replied</b>\\nTap the author when a reply arrives.",kb)

async def auto_send_message(chat,uid,mid,gid=None):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    if gid:
        sender=row("SELECT * FROM gmail_accounts WHERE id=:g AND telegram_user_id=:u",g=gid,u=uid)
    else:
        sender=row("SELECT * FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id LIMIT 1",u=uid)
    if not sender:return await send(chat,"🔒 Automatic sending is disabled until Gmail is connected. Use /gmail first.")
    m=row("""SELECT m.*,p.name,COALESCE(NULLIF(m.recipient_email,''),p.email) recipient
        FROM messages m JOIN prospects p ON p.id=m.prospect_id
        WHERE m.id=:m AND m.team_id=:t""",m=mid,t=t["id"])
    if not m:return await send(chat,"Message not found.")
    if not m["recipient"]:return await send(chat,"This author has no recipient email.")
    if m["status"]=="sent":return await send(chat,"This message is already marked sent.")
    try:
        await gmail_send(sender,m["recipient"],m["subject"],m["body"])
        execq("""UPDATE messages SET status='sent',sender_email=:e,sent_by_user_id=:u,sent_at=:d,updated_at=:d,sent_via='gmail_api',auto_sent=1
            WHERE id=:m AND team_id=:t""",e=sender["email"],u=uid,d=iso(),m=mid,t=t["id"])
        await send(chat,f"✅ Sent automatically from <code>{esc(sender['email'])}</code> to <code>{esc(m['recipient'])}</code>.")
        return await queue(chat,uid)
    except Exception as e:
        print(f"AUTO_SEND_ERROR {type(e).__name__}: {e}")
        return await send(chat,"Automatic send failed. The message was not marked sent. Check Gmail connection and try again.")

def main_menu():
    return {"inline_keyboard":[
        [{"text":"🔎 Scout Authors","callback_data":"menu:scout"},{"text":"📥 Download for ChatGPT","callback_data":"menu:export"}],
        [{"text":"📤 Upload ChatGPT File","callback_data":"menu:upload"},{"text":"📨 Message Queue","callback_data":"menu:queue"}],
        [{"text":"📊 Campaign Stats","callback_data":"menu:campaign"},{"text":"📬 Replies","callback_data":"menu:replies"}],
        [{"text":"🔗 Gmail","callback_data":"menu:gmail"},{"text":"⚡ Automatic Sending","callback_data":"menu:auto"}],
        [{"text":"🔍 Last Search","callback_data":"menu:lastsearch"},{"text":"👥 Team","callback_data":"menu:team"}],
        [{"text":"📘 How to Use","callback_data":"menu:howto"},{"text":"❓ Help","callback_data":"menu:help"}]
    ]}

async def last_search(chat,uid):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    r=row("SELECT * FROM search_runs WHERE team_id=:t ORDER BY id DESC LIMIT 1",t=t["id"])
    if not r:return await send(chat,"No completed search has been recorded yet.")
    try:routes=json.loads(r["search_routes"] or "[]")
    except:routes=[]
    lines="\\n".join([f"{i+1}. <code>{esc(q)}</code>" for i,q in enumerate(routes)])
    return await send(chat,
        f"<b>🔍 Last search</b>\\n"
        f"Request: <code>{esc(r['request_text'])}</code>\\n"
        f"Raw results: <b>{r['raw_results']}</b>\\n"
        f"Candidates: <b>{r['candidates']}</b>\\n"
        f"Checked: <b>{r['checked']}</b>\\n"
        f"Accepted: <b>{r['accepted']}</b>\\n"
        f"Duplicates: <b>{r['duplicates']}</b>\\n\\n"
        f"<b>Exact search routes used</b>\\n{lines or 'None'}"
    )

async def live_test(chat,uid,mid,gid):
    t=team(uid)
    m=row("SELECT m.*,p.name,p.email FROM messages m JOIN prospects p ON p.id=m.prospect_id WHERE m.id=:m AND m.team_id=:t",m=mid,t=t["id"])
    sender=row("SELECT * FROM gmail_accounts WHERE id=:g AND telegram_user_id=:u",g=gid,u=uid)
    if not m or not sender: return await send(chat,"Message or Gmail account not found.")
    pool=rows("""SELECT g.*,u.team_id FROM gmail_accounts g JOIN users u ON u.telegram_user_id=g.telegram_user_id
      WHERE g.test_opt_in=1 AND lower(g.email)<>:e AND (g.test_scope='global' OR u.team_id=:t)""",e=sender["email"].lower(),t=t["id"])
    random.shuffle(pool); pool=pool[:10]
    if not pool:return await send(chat,"No opted-in test inboxes are available yet.")
    with engine.begin() as c:
        r=c.execute(text("INSERT INTO delivery_tests(team_id,requested_by_user_id,message_id,sender_gmail_id,sender_email,requested_count,sent_count,status,created_at) VALUES(:t,:u,:m,:g,:e,10,0,'sending',:d) RETURNING id"),{"t":t["id"],"u":uid,"m":mid,"g":gid,"e":sender["email"],"d":iso()});test_id=int(r.scalar_one())
    sent=0
    for a in pool:
        try:
            await gmail_send(sender,a["email"],m["subject"],m["body"])
            execq("INSERT INTO delivery_test_recipients(test_id,gmail_account_id,owner_user_id,email,result,sent_at) VALUES(:t,:g,:u,:e,'pending',:d)",t=test_id,g=a["id"],u=a["telegram_user_id"],e=a["email"],d=iso());sent+=1
            kb={"inline_keyboard":[[{"text":"Inbox","callback_data":f"place:{test_id}:{a['id']}:inbox"},{"text":"Spam","callback_data":f"place:{test_id}:{a['id']}:spam"}],[{"text":"Promotions","callback_data":f"place:{test_id}:{a['id']}:promotions"},{"text":"Not received","callback_data":f"place:{test_id}:{a['id']}:not_received"}]]}
            await send(a["telegram_user_id"],f"🧪 <b>Deliverability test</b>\nCheck <code>{esc(a['email'])}</code> for a message from <code>{esc(sender['email'])}</code>, then report where it landed.",kb)
        except Exception:pass
    execq("UPDATE delivery_tests SET sent_count=:s,status='waiting' WHERE id=:i",s=sent,i=test_id)
    await send(chat,f"🧪 Test #{test_id} sent to <b>{sent}</b> opted-in inboxes.\nUse /deliverytests to see reports.")

def test_report(test_id):
    rs=rows("SELECT result,COUNT(*) c FROM delivery_test_recipients WHERE test_id=:i GROUP BY result",i=test_id)
    d={r["result"]:r["c"] for r in rs}; total=sum(d.values())
    return total,d

async def cmd_stats(chat,uid,arg=""):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    n=now().astimezone(TZ); start=n.replace(hour=0,minute=0,second=0,microsecond=0).astimezone(timezone.utc)
    y=start-timedelta(days=1); seven=start-timedelta(days=6)
    def count(s,e):return int((row("SELECT COUNT(*) c FROM scout_events WHERE team_id=:t AND created_at>=:s AND created_at<:e",t=t["id"],s=iso(s),e=iso(e)) or {"c":0})["c"])
    today=count(start,now()+timedelta(seconds=1)); yesterday=count(y,start); last7=count(seven,now()+timedelta(seconds=1))
    def leader(s,e):
        return row("""SELECT u.first_name,u.username,COUNT(*) c FROM scout_events x JOIN users u ON u.telegram_user_id=x.telegram_user_id
          WHERE x.created_at>=:s AND x.created_at<:e GROUP BY x.telegram_user_id,u.first_name,u.username ORDER BY c DESC LIMIT 1""",s=iso(s),e=iso(e))
    ld=leader(start,now()+timedelta(seconds=1)); l5=leader(now()-timedelta(hours=5),now()+timedelta(seconds=1))
    name=lambda r:(r["first_name"] or ("@"+r["username"] if r.get("username") else "Unknown")) if r else "No scout"
    custom=""
    if arg:
        p=arg.split()
        if len(p)==2:
            try:
                s=datetime.strptime(p[0],"%Y-%m-%d").replace(tzinfo=TZ).astimezone(timezone.utc);e=datetime.strptime(p[1],"%Y-%m-%d").replace(tzinfo=TZ).astimezone(timezone.utc)+timedelta(days=1)
                custom=f"\nSelected range: <b>{count(s,e)}</b>"
            except:custom="\nUse /stats YYYY-MM-DD YYYY-MM-DD"
    await send(chat,f"<b>{esc(t['name'])} stats</b>\nToday: <b>{today}</b>\nYesterday: <b>{yesterday}</b>\nLast 7 days: <b>{last7}</b>{custom}\n\n🏆 Today: <b>{esc(name(ld))}</b> ({ld['c'] if ld else 0})\n🔥 Last 5 hours: <b>{esc(name(l5))}</b> ({l5['c'] if l5 else 0})")

async def import_sheet(chat,uid,doc):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    info=await tg("getFile",{"file_id":doc["file_id"]});ext=Path(doc.get("file_name") or "x.xlsx").suffix.lower()
    async with httpx.AsyncClient(timeout=60) as hc:
        r=await hc.get(f"{TGFILE}/{info['file_path']}");r.raise_for_status();data=r.content
    if ext==".csv":
        table=list(csv.reader(io.StringIO(data.decode("utf-8-sig"))))
    elif ext in {".xlsx",".xlsm"}:
        book=load_workbook(io.BytesIO(data),read_only=True,data_only=True)
        sh=book["Authors & Messages"] if "Authors & Messages" in book.sheetnames else book.active
        table=[list(x) for x in sh.iter_rows(values_only=True)]
    else:
        return await send(chat,"Upload an XLSX or CSV file.")
    if not table:return await send(chat,"The uploaded file is empty.")
    h=[norm_header(x) for x in table[0]]
    def ix(names):
        wanted={norm_header(n) for n in names}
        for i,n in enumerate(h):
            if n in wanted:return i
        return None
    iid=ix(["Canonical Author ID","Source Row ID"])
    ia=ix(["Author Name — Verified","Author","Author Name","Name","Author Name — Bot"])
    ie=ix(["Public Professional Email","Verified Public Email","Email","Author Email","Public Professional Email — Bot"])
    iw=ix(["Official Website","Verified Official Website","Website"])
    ies=ix(["Email Source URL"])
    ist=ix(["Processing Status"])
    isub=ix(["Selected Subject","Subject","Subject Line","Subject Option 1"])
    ib=ix(["Best First Message — Author Language","First Message","Message","Body","Email Body"])
    ibe=ix(["Best First Message — English","English Version"])
    if isub is None or ib is None:
        return await send(chat,"I found the file, but it needs the ChatGPT output columns <b>Selected Subject</b> and <b>Best First Message — Author Language</b>.")
    ps=rows("SELECT * FROM prospects WHERE claimed_team_id=:t",t=t["id"])
    byid={f"as-{p['id']}":p for p in ps};bn={p["name"].lower():p for p in ps};be={p["email"].lower():p for p in ps if p["email"]}
    matched=ready=skipped=unmatched=0
    for rr in table[1:]:
        g=lambda i:str(rr[i] or "").strip() if i is not None and i<len(rr) else ""
        p=None
        if iid is not None:
            rid=g(iid).lower()
            p=byid.get(rid)
        if not p and ie is not None:p=be.get(g(ie).lower())
        if not p and ia is not None:p=bn.get(g(ia).lower())
        if not p:
            unmatched+=1;continue
        subject=g(isub);body=g(ib)
        if not subject or not body:
            skipped+=1;continue
        status=g(ist).upper() if ist is not None else ""
        if status and status not in {"COMPLETED","READY","READY FOR OUTREACH"}:
            skipped+=1;continue
        recipient=g(ie) or p["email"];english=g(ibe)
        ex=row("SELECT id,status FROM messages WHERE team_id=:t AND prospect_id=:p ORDER BY id DESC LIMIT 1",t=t["id"],p=p["id"])
        vals={"t":t["id"],"p":p["id"],"u":uid,"s":subject,"b":body,"be":english,"re":recipient.lower(),"d":iso()}
        if ex:
            execq("""UPDATE messages SET subject=:s,body=:b,body_english=:be,recipient_email=:re,
                status=CASE WHEN status='sent' THEN status ELSE 'ready' END,updated_at=:d WHERE id=:i""",
                s=subject,b=body,be=english,re=recipient.lower(),d=iso(),i=ex["id"])
        else:
            execq("""INSERT INTO messages(team_id,prospect_id,imported_by_user_id,subject,body,body_english,recipient_email,status,created_at,updated_at)
                VALUES(:t,:p,:u,:s,:b,:be,:re,'ready',:d,:d)""",**vals)
        matched+=1;ready+=1
    await send(chat,
        f"✅ ChatGPT file imported.\\n"
        f"Matched authors: <b>{matched}</b>\\n"
        f"Ready messages: <b>{ready}</b>\\n"
        f"Skipped/no final message: <b>{skipped}</b>\\n"
        f"Unmatched rows: <b>{unmatched}</b>\\n\\n"
        f"Use /queue to start sending."
    )

async def queue(chat,uid,skip=None):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    q=rows("""SELECT m.*,p.name,COALESCE(NULLIF(m.recipient_email,''),p.email) recipient
        FROM messages m JOIN prospects p ON p.id=m.prospect_id
        WHERE m.team_id=:t AND m.status='ready' ORDER BY m.id""",t=t["id"])
    if skip:q=[x for x in q if x["id"]!=skip]+[x for x in q if x["id"]==skip]
    if not q:return await send(chat,"No unsent messages. Use /campaign to see your current totals.")
    m=q[0];token=serializer.dumps({"uid":uid,"mid":m["id"]});url=f"{BASE}/compose?t={token}" if BASE else "https://mail.google.com/"
    has_gmail=bool(row("SELECT id FROM gmail_accounts WHERE telegram_user_id=:u LIMIT 1",u=uid))
    auto_text="⚡ Auto Send" if has_gmail else "🔒 Auto Send"
    kb={"inline_keyboard":[
        [{"text":"📨 Open Gmail","url":url},{"text":"✅ Mark Sent","callback_data":f"sent:{m['id']}"}],
        [{"text":auto_text,"callback_data":f"autosend:{m['id']}"},{"text":"⏭ Skip","callback_data":f"skip:{m['id']}"}],
        [{"text":"🧪 Deliverability Test","callback_data":f"test:{m['id']}"},{"text":"📊 Stats","callback_data":"menu:campaign"}]
    ]}
    await send(chat,
        f"<b>{esc(m['name'])}</b>\\n"
        f"To: <code>{esc(m['recipient'] or 'no email')}</code>\\n\\n"
        f"<b>Subject</b>\\n{esc(m['subject'])}\\n\\n"
        f"<b>Message</b>\\n{esc(m['body'])}\\n\\n"
        f"<b>{len(q)}</b> message(s) ready",
        kb
    )

HOWTO="""<b>📘 HOW TO USE AUTHOR SCOUT TEAM BOT</b>

<b>What this bot does</b>
Author Scout helps a team discover authors, prevent duplicates, prepare research files for ChatGPT, import the finished outreach messages, send them, and track campaign activity.

<b>1. Join or create a team</b>
• Create: <code>/newteam Team Name</code>
• Join: <code>/join CODE</code>
• View your team: <code>/team</code>

Each team has its own workspace, but author deduplication is global. If an author has already been claimed anywhere in the bot, the bot blocks the duplicate.

<b>2. Scout authors</b>
You can type naturally:
<code>Karim in Saudi Arabia</code>
<code>10 fantasy authors in Canada with public email</code>
<code>Arabic writers in UAE active in 2026</code>

Or use explicit filters:
<code>/find country=UAE genre=fiction gender=male email=yes website=yes count=10</code>

The bot searches public web sources, checks author identity, website, public professional email, email source, recent activity and source URLs, then saves accepted unique authors.

Use <code>/lastsearch</code> to see the exact search routes used and the result counts.

<b>3. Review authors</b>
Use <code>/authors</code> to see recently scouted authors.

The Telegram bot is for discovery and workflow. ChatGPT performs the deeper research and creates the best first message.

<b>4. Download the ChatGPT research file</b>
Use <code>/export</code> or tap <b>Download for ChatGPT</b>.

The XLSX includes:
• stable AS- author IDs
• author name
• country / genre
• website
• public professional email
• email source URL
• verification status
• bio / research seed
• books
• recent activity
• source URLs
• all research/message output columns
• HOW TO USE sheet
• the full Master Author Research & Messaging System v3.2 prompt

<b>5. Research in ChatGPT</b>
Upload the exported XLSX to ChatGPT.

Tell ChatGPT to read the embedded <b>ChatGPT Prompt</b> sheet and process every author.

ChatGPT should deeply verify each author, research the current situation, representation/rights, opportunities, sources, personalization, subject lines and the strongest first message.

It must preserve:
• Source Row ID
• Canonical Author ID
• every original Bot column

ChatGPT should return a new XLSX with the completed research and message fields.

<b>6. Upload ChatGPT's finished file</b>
Upload that XLSX directly back into this Telegram chat.

The bot matches each row using the AS- ID first, then email/name as fallback.

For outreach-ready rows it imports:
• recipient email
• selected subject
• best first message in the author's language
• English version

Use <code>/queue</code> after import.

<b>7. Send messages</b>
The queue shows one author at a time with the full recipient, subject and message.

You can:
• <b>Open Gmail</b> for manual sending
• <b>Mark Sent</b>
• <b>Skip</b>
• run a deliverability test
• use <b>Auto Send</b> if Gmail is connected

<b>8. Automatic sending</b>
Automatic sending is locked until the user successfully connects Gmail.

Use <code>/gmail</code> to connect Gmail.

Use <code>/autosend</code> to check automatic-send availability.

A user without a connected Gmail account cannot use automatic sending.

<b>9. Track replies and results</b>
Use <code>/replies</code> to mark authors who have replied.

Use <code>/campaign</code> to see:
• authors scouted
• messages imported
• messages ready
• messages sent
• replies
• reply rate

For a period:
<code>/campaign 2026-09-01 2026-09-15</code>

Use <code>/leaderboard</code> for team scouting activity.

<b>10. Main workflow</b>
Scout → Export → ChatGPT Research → Upload ChatGPT XLSX → Queue → Send → Track Replies → Campaign Stats

<b>Useful commands</b>
<code>/menu</code> Main buttons
<code>/find</code> Scout authors
<code>/authors</code> Recent authors
<code>/lastsearch</code> Exact last search
<code>/export</code> ChatGPT-ready XLSX
<code>/brief</code> Download workflow brief
<code>/queue</code> Outreach queue
<code>/gmail</code> Gmail connection
<code>/autosend</code> Automatic-send status
<code>/replies</code> Mark replies
<code>/campaign</code> Campaign totals
<code>/stats</code> Team stats
<code>/leaderboard</code> Team leaderboard
<code>/team</code> Team details
<code>/help</code> Quick command help
<code>/howto</code> This complete guide""" 

HELP="""<b>Author Scout Team Bot</b>

<b>Scout</b>
/find Karim in Saudi Arabia
/find country=UAE genre=fiction gender=male email=yes
/research Author Name
/authors
/lastsearch

<b>ChatGPT handoff</b>
/export — download ChatGPT-ready XLSX with the research prompt embedded
/brief — download the workflow instructions
Upload ChatGPT's returned XLSX/CSV directly to the bot.

<b>Outreach</b>
/queue — ready messages
/replies — mark author replies
/campaign — authors, ready, sent and replies
/campaign YYYY-MM-DD YYYY-MM-DD
/gmail — connect Gmail and manage test inboxes
/autosend — automatic sending status
/deliverytests

<b>Team</b>
/newteam Team Name
/join CODE
/team
/stats
/leaderboard
/menu
/howto — complete step-by-step guide

The same prospect is blocked globally from being claimed twice."""

async def handle(up):
    if up.get("callback_query"):
        cb=up["callback_query"];uid=ensure_user(cb["from"]);chat=cb["message"]["chat"]["id"];await tg("answerCallbackQuery",{"callback_query_id":cb["id"]});d=cb.get("data","");t=team(uid)
        if d=="menu:scout":
            set_user_state(uid,"awaiting_find_query")
            return await send(chat,
                "🔎 <b>What authors do you want me to scout?</b>\n\n"
                "Send the search request first. I will not search until you do.\n\n"
                "Examples:\n"
                "• <code>10 emerging fantasy authors in Canada with public email</code>\n"
                "• <code>25 Spanish male authors active in 2026 with website and email</code>\n"
                "• <code>UAE authors writing literary fiction, low saturation</code>\n\n"
                "Use /cancel to stop.")
        if d=="menu:export":return await export_chatgpt(chat,uid)
        if d=="menu:upload":return await send(chat,"📤 Upload the XLSX that ChatGPT returned. I will match authors by AS- ID first and import the selected subject + final first message.")
        if d=="menu:queue":return await queue(chat,uid)
        if d=="menu:campaign":return await campaign(chat,uid)
        if d=="menu:replies":return await replies_view(chat,uid)
        if d=="menu:gmail":
            acs=rows("SELECT * FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id",u=uid);lines=["<b>Gmail / test inboxes</b>"]+[f"• {esc(a['email'])} — {'ON '+a['test_scope'] if a['test_opt_in'] else 'OFF'}" for a in acs]
            kb={"inline_keyboard":[]}
            if gmail_ok():kb["inline_keyboard"].append([{"text":"➕ Connect Gmail","url":f"{BASE}/oauth/google/start?t="+serializer.dumps({'uid':uid})}])
            for a in acs:kb["inline_keyboard"] += [[{"text":"Team pool","callback_data":f"opt:{a['id']}:team"},{"text":"Global pool","callback_data":f"opt:{a['id']}:global"},{"text":"Off","callback_data":f"off:{a['id']}"}]]
            return await send(chat,"\n".join(lines) if len(lines)>1 else "<b>Gmail</b>\nNo Gmail account connected yet.",kb if kb["inline_keyboard"] else None)
        if d=="menu:auto":
            a=row("SELECT email FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id LIMIT 1",u=uid)
            return await send(chat,f"⚡ Automatic sending is enabled through <code>{esc(a['email'])}</code>. Open /queue and tap Auto Send." if a else "🔒 Automatic sending is disabled until Gmail is connected. Use /gmail.")
        if d=="menu:lastsearch":return await last_search(chat,uid)
        if d=="menu:team":
            t=team(uid);return await send(chat,f"<b>{esc(t['name'])}</b>\nInvite: <code>{t['invite_code']}</code>" if t else "No team.")
        if d=="menu:howto":return await send(chat,HOWTO,main_menu())
        if d=="menu:help":return await send(chat,HELP,main_menu())
        if d.startswith("autosend:"):return await auto_send_message(chat,uid,int(d.split(":")[1]))
        if d.startswith("replied:") and t:
            mid=int(d.split(":")[1]);execq("UPDATE messages SET reply_status='replied',replied_at=:d,updated_at=:d WHERE id=:m AND team_id=:t",d=iso(),m=mid,t=t["id"])
            await send(chat,"✅ Reply recorded.");return await replies_view(chat,uid)
        if d.startswith("sent:") and t:
            mid=int(d.split(":")[1]);execq("UPDATE messages SET status='sent',sent_by_user_id=:u,sent_at=:d,updated_at=:d,sent_via='manual' WHERE id=:m AND team_id=:t",u=uid,d=iso(),m=mid,t=t["id"]);return await queue(chat,uid)
        if d.startswith("skip:"):return await queue(chat,uid,int(d.split(":")[1]))
        if d.startswith("test:") and t:
            mid=int(d.split(":")[1]);acs=rows("SELECT id,email FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id",u=uid)
            if not acs:return await send(chat,"Connect Gmail first with /gmail.")
            kb={"inline_keyboard":[[{"text":a["email"],"callback_data":f"run:{mid}:{a['id']}"}] for a in acs]};return await send(chat,"Choose the Gmail sender for this live test:",kb)
        if d.startswith("run:"):
            _,mid,gid=d.split(":");return await live_test(chat,uid,int(mid),int(gid))
        if d.startswith("place:"):
            _,tid,gid,res=d.split(":");a=row("SELECT * FROM gmail_accounts WHERE id=:g AND telegram_user_id=:u",g=int(gid),u=uid)
            if a:
                execq("UPDATE delivery_test_recipients SET result=:r,responded_at=:d WHERE test_id=:t AND gmail_account_id=:g",r=res,d=iso(),t=int(tid),g=int(gid))
                total,stats=test_report(int(tid));test=row("SELECT requested_by_user_id FROM delivery_tests WHERE id=:i",i=int(tid))
                await send(chat,"✅ Placement recorded.")
                if test:await send(test["requested_by_user_id"],f"🧪 Test #{tid} update\nInbox: {stats.get('inbox',0)}\nPromotions: {stats.get('promotions',0)}\nSpam: {stats.get('spam',0)}\nNot received: {stats.get('not_received',0)}\nPending: {stats.get('pending',0)}")
            return
        if d.startswith("opt:"):
            _,gid,scope=d.split(":");execq("UPDATE gmail_accounts SET test_opt_in=1,test_scope=:s,updated_at=:d WHERE id=:g AND telegram_user_id=:u",s=scope,d=iso(),g=int(gid),u=uid);return await send(chat,f"✅ Test inbox enabled ({scope}).")
        if d.startswith("off:"):
            gid=int(d.split(":")[1]);execq("UPDATE gmail_accounts SET test_opt_in=0,updated_at=:d WHERE id=:g AND telegram_user_id=:u",d=iso(),g=gid,u=uid);return await send(chat,"✅ Test inbox disabled.")
        return
    m=up.get("message") or {};u=m.get("from") or {};uid=u.get("id");chat=(m.get("chat") or {}).get("id")
    if not uid or not chat:return
    uid=ensure_user(u);t=team(uid)
    if m.get("document"):return await import_sheet(chat,uid,m["document"])
    txt=(m.get("text") or "").strip();parts=txt.split(maxsplit=1);cmd=parts[0].split("@")[0].lower() if txt.startswith("/") else "";arg=parts[1] if len(parts)>1 else ""
    if not cmd and txt:
        state=get_user_state(uid)
        if state and state.get("state")=="awaiting_find_query":
            cmd="/find";arg=txt
            clear_user_state(uid)
        else:
            natural=re.match(r"(?i)^(?:find|search|scout)\\s+(.+)$",txt)
            if natural:
                cmd="/find";arg=natural.group(1).strip()
    if cmd=="/cancel":
        clear_user_state(uid)
        return await send(chat,"✅ Cancelled. No search was started.",main_menu())
    if cmd=="/howto":return await send(chat,HOWTO,main_menu())
    if cmd in {"/start","/help","/menu"}:
        return await send(chat,HELP,main_menu())
    if cmd=="/newteam":
        if t:return await send(chat,"You are already in a team.")
        if not arg:return await send(chat,"Use /newteam Team Name")
        code=invite()
        with engine.begin() as c:
            r=c.execute(text("INSERT INTO teams(name,invite_code,owner_user_id,created_at) VALUES(:n,:c,:u,:d) RETURNING id"),{"n":arg,"c":code,"u":uid,"d":iso()});tid=int(r.scalar_one());c.execute(text("UPDATE users SET team_id=:t,updated_at=:d WHERE telegram_user_id=:u"),{"t":tid,"d":iso(),"u":uid})
        return await send(chat,f"✅ Team created. Invite code: <code>{code}</code>")
    if cmd=="/join":
        if t:return await send(chat,"You are already in a team.")
        x=row("SELECT * FROM teams WHERE invite_code=:c",c=arg.strip().upper())
        if not x:return await send(chat,"Invalid invite code.")
        execq("UPDATE users SET team_id=:t,updated_at=:d WHERE telegram_user_id=:u",t=x["id"],d=iso(),u=uid);return await send(chat,f"✅ Joined <b>{esc(x['name'])}</b>.")
    if cmd=="/team":
        t=team(uid);return await send(chat,f"<b>{esc(t['name'])}</b>\nInvite: <code>{t['invite_code']}</code>" if t else "No team.")
    if cmd=="/find":
        t=team(uid)
        if not t:return await send(chat,"Join/create a team first.")
        if not arg.strip():
            set_user_state(uid,"awaiting_find_query")
            return await send(chat,
                "🔎 <b>What authors do you want me to scout?</b>\n\n"
                "I will wait for your search query before doing any research.\n\n"
                "Be as specific as you want, for example:\n"
                "<code>10 emerging fantasy authors in Canada with verified public email and website</code>\n\n"
                "Use /cancel to stop.")
        clear_user_state(uid)
        spec=parse_find(arg)
        if not find_query_is_specific(spec):
            set_user_state(uid,"awaiting_find_query")
            return await send(chat,
                "That search is too broad. No research has started.\n\n"
                "Add at least one useful target such as country, genre, author name, language, career stage, or current activity.\n"
                "Example: <code>10 emerging fantasy authors in Canada active in 2026</code>")

        status=await send(
            chat,
            f"🚀 <b>Scout started</b>\n"
            f"Target: {spec['count']} new authors\n"
            f"Search: {esc(spec.get('query') or spec.get('name') or 'authors')}\n"
            f"Country: {esc(spec.get('country') or 'any')}\n"
            f"Genre: {esc(spec.get('genre') or 'any')}\n"
            f"Gender: {esc(spec.get('gender') or 'any')}\n"
            f"Email required: {'yes' if spec.get('require_email') else 'no'}\n"
            f"Website required: {'yes' if spec.get('require_website') else 'no'}"
        )
        status_id=status.get("message_id") if isinstance(status,dict) else None
        async def progress(message):
            if status_id:
                await edit_msg(chat,status_id,message)
            else:
                await send(chat,message)
        found,meta=await find_authors(spec,progress)
        n=spec["count"];new=dup=0
        if not found:
            execq("""INSERT INTO search_runs(team_id,telegram_user_id,request_text,parsed_spec,search_routes,raw_results,candidates,checked,accepted,duplicates,created_at)
                VALUES(:t,:u,:r,:p,:q,:raw,:c,:ch,0,0,:d)""",t=t["id"],u=uid,r=arg,p=json.dumps(spec),q=json.dumps(meta.get("queries",[])),raw=meta["raw_results"],c=meta["candidates"],ch=meta["checked"],d=iso())
            return await progress(
                f"⚠️ <b>Scout finished with no verified matches</b>\n"
                f"Raw search results: <b>{meta['raw_results']}</b>\n"
                f"Candidate names: <b>{meta['candidates']}</b>\n"
                f"Candidates checked: <b>{meta['checked']}</b>\n"
                f"Websites found: <b>{meta['with_website']}</b>\n"
                f"Public emails found: <b>{meta['with_email']}</b>\n"
                f"Search used: <code>{esc(meta['query'])}</code>\n\n"
                f"No prospects were saved. This tells us exactly which stage needs adjustment."
            )
        for idx,d in enumerate(found,1):
            _,created,_=claim(uid,t["id"],d)
            new+=int(created);dup+=int(not created)
            await progress(
                f"💾 <b>Saving verified authors</b>\n"
                f"Processed: {idx}/{len(found)}\n"
                f"New claimed: <b>{new}</b> / {n}\n"
                f"Duplicates blocked: <b>{dup}</b>"
            )
            if new>=n:break
        execq("""INSERT INTO search_runs(team_id,telegram_user_id,request_text,parsed_spec,search_routes,raw_results,candidates,checked,accepted,duplicates,created_at)
            VALUES(:t,:u,:r,:p,:q,:raw,:c,:ch,:a,:du,:d)""",t=t["id"],u=uid,r=arg,p=json.dumps(spec),q=json.dumps(meta.get("queries",[])),raw=meta["raw_results"],c=meta["candidates"],ch=meta["checked"],a=new,du=dup,d=iso())
        return await progress(
            f"✅ <b>Scout complete</b>\n"
            f"New claimed: <b>{new}</b>\n"
            f"Duplicates blocked: <b>{dup}</b>\n"
            f"Candidates checked: <b>{meta['checked']}</b>\n"
            f"Public emails found: <b>{meta['with_email']}</b>"
        )
    if cmd=="/research":
        t=team(uid)
        if not t:return await send(chat,"Join/create a team first.")
        d=await research(arg);pid,created,ex=claim(uid,t["id"],d)
        return await send(chat,f"✅ Claimed {esc(d['name'])}" if created else f"⚠️ Already scouted: {esc(ex['name'])}")
    if cmd=="/authors":
        t=team(uid);ps=rows("SELECT * FROM prospects WHERE claimed_team_id=:t ORDER BY id DESC LIMIT 30",t=t["id"]) if t else []
        return await send(chat,"\n".join([f"• {esc(p['name'])} — {esc(p['email'] or 'no email')}" for p in ps]) or "No authors.")
    if cmd=="/export":return await export_chatgpt(chat,uid)
    if cmd=="/brief":return await send_brief(chat,uid)
    if cmd=="/lastsearch":return await last_search(chat,uid)
    if cmd=="/campaign":return await campaign(chat,uid,arg)
    if cmd=="/replies":return await replies_view(chat,uid)
    if cmd=="/autosend":
        a=row("SELECT email FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id LIMIT 1",u=uid)
        return await send(chat,f"⚡ Automatic sending is enabled through <code>{esc(a['email'])}</code>. Use /queue and tap Auto Send on the message you approve." if a else "🔒 Automatic sending is disabled. Connect Gmail with /gmail first.")
    if cmd=="/stats":
        await campaign(chat,uid,arg)
        return
    if cmd=="/leaderboard":
        s=now().astimezone(TZ).replace(hour=0,minute=0,second=0,microsecond=0).astimezone(timezone.utc);ls=rows("SELECT u.first_name,u.username,COUNT(*) c FROM scout_events x JOIN users u ON u.telegram_user_id=x.telegram_user_id WHERE x.created_at>=:s GROUP BY x.telegram_user_id,u.first_name,u.username ORDER BY c DESC LIMIT 10",s=iso(s));return await send(chat,"<b>🏆 Today</b>\n"+"\n".join([f"{i+1}. {esc(r['first_name'] or '@'+r['username'])} — {r['c']}" for i,r in enumerate(ls)]))
    if cmd=="/queue":return await queue(chat,uid)
    if cmd=="/gmail":
        acs=rows("SELECT * FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id",u=uid);lines=["<b>Gmail / test inboxes</b>"]+[f"• {esc(a['email'])} — {'ON '+a['test_scope'] if a['test_opt_in'] else 'OFF'}" for a in acs]
        kb={"inline_keyboard":[]}
        if gmail_ok():kb["inline_keyboard"].append([{"text":"➕ Connect Gmail","url":f"{BASE}/oauth/google/start?t="+serializer.dumps({'uid':uid})}])
        for a in acs:kb["inline_keyboard"] += [[{"text":"Team pool","callback_data":f"opt:{a['id']}:team"},{"text":"Global pool","callback_data":f"opt:{a['id']}:global"},{"text":"Off","callback_data":f"off:{a['id']}"}]]
        return await send(chat,"\n".join(lines),kb if kb["inline_keyboard"] else None)
    if cmd=="/deliverytests":
        ts=rows("SELECT * FROM delivery_tests WHERE requested_by_user_id=:u ORDER BY id DESC LIMIT 10",u=uid);out=["<b>Your tests</b>"]
        for x in ts:
            total,st=test_report(x["id"]);out.append(f"#{x['id']} — sent {x['sent_count']} — inbox {st.get('inbox',0)} / spam {st.get('spam',0)} / promotions {st.get('promotions',0)} / pending {st.get('pending',0)}")
        return await send(chat,"\n".join(out))
    return await send(chat,"Use /help.")

@app.on_event("startup")
async def startup():
    raw_db=os.getenv("DATABASE_URL","")
    try:
        p=urlparse(raw_db if raw_db else "sqlite:///./scoutbot.db")
        print(f"DB_DIAGNOSTIC configured={bool(raw_db)} scheme={p.scheme or 'sqlite'} host={p.hostname or ''} database={(p.path or '').lstrip('/') or 'scoutbot.db'}")
    except Exception:
        print(f"DB_DIAGNOSTIC configured={bool(raw_db)} scheme=unknown host= database=")
    init_db()
    if TOKEN and BASE and WEBHOOK_SECRET:
        try:
            me=await tg("getMe")
            print(f"TG_DIAGNOSTIC token_ok=True bot=@{me.get('username','')}")
            await tg("setWebhook",{"url":f"{BASE}/telegram/webhook","secret_token":WEBHOOK_SECRET})
            info=await tg("getWebhookInfo")
            print(f"TG_WEBHOOK url={info.get('url','')} pending={info.get('pending_update_count',0)} last_error={info.get('last_error_message','')}")
            await tg("setMyCommands",{"commands":json.dumps([
                {"command":"menu","description":"Open Author Scout menu"},
                {"command":"find","description":"Scout authors using filters or natural language"},
                {"command":"authors","description":"Show recently scouted authors"},
                {"command":"lastsearch","description":"Show exact last search routes"},
                {"command":"export","description":"Download ChatGPT-ready author workbook"},
                {"command":"queue","description":"Open ready outreach messages"},
                {"command":"campaign","description":"Show authors, sent and reply totals"},
                {"command":"replies","description":"Mark author replies"},
                {"command":"gmail","description":"Connect Gmail / deliverability settings"},
                {"command":"autosend","description":"Automatic sending status"},
                {"command":"team","description":"Show team and invite code"},
                {"command":"howto","description":"Complete Author Scout workflow guide"},
                {"command":"help","description":"Show help"}
            ])})
        except Exception as e:
            print(f"TG_DIAGNOSTIC token_ok=False error={type(e).__name__}: {e}")

@app.get("/")
async def root():return {"ok":True,"name":"Author Scout Team Bot","version":"2.0"}
@app.get("/health")
async def health():return {"ok":True}

@app.get("/debug/db")
async def debug_db():
    raw=os.getenv("DATABASE_URL","")
    try:
        p=urlparse(raw if raw else "sqlite:///./scoutbot.db")
        return {
            "configured": bool(raw),
            "scheme": p.scheme or "sqlite",
            "host": p.hostname or "",
            "database": (p.path or "").lstrip("/") or "scoutbot.db"
        }
    except Exception:
        return {"configured": bool(raw), "scheme": "unknown", "host": "", "database": ""}
async def safe_handle(update):
    try:
        await handle(update)
    except Exception as e:
        import traceback
        print(f"HANDLER_ERROR {type(e).__name__}: {e}")
        traceback.print_exc()

@app.post("/telegram/webhook")
async def webhook(request:Request,x_telegram_bot_api_secret_token:str|None=Header(default=None)):
    if x_telegram_bot_api_secret_token!=WEBHOOK_SECRET:raise HTTPException(403)
    asyncio.create_task(safe_handle(await request.json()));return {"ok":True}

@app.get("/oauth/google/start")
async def oauth_start(t:str):
    if not gmail_ok():raise HTTPException(503,"Gmail OAuth not configured")
    p=serializer.loads(t,max_age=900);state=serializer.dumps({"uid":int(p["uid"])})
    return RedirectResponse(GOOGLE_AUTH+"?"+urlencode({"client_id":GOOGLE_CLIENT_ID,"redirect_uri":GOOGLE_REDIRECT_URI,"response_type":"code","scope":GMAIL_SCOPE,"access_type":"offline","prompt":"consent","state":state}))

@app.get("/oauth/google/callback")
async def oauth_callback(code:str,state:str,error:str=""):
    if error:return HTMLResponse("Gmail connection cancelled.",400)
    p=serializer.loads(state,max_age=900);uid=int(p["uid"])
    async with httpx.AsyncClient(timeout=30) as c:
        tr=await c.post(GOOGLE_TOKEN,data={"client_id":GOOGLE_CLIENT_ID,"client_secret":GOOGLE_CLIENT_SECRET,"code":code,"grant_type":"authorization_code","redirect_uri":GOOGLE_REDIRECT_URI});tr.raise_for_status();td=tr.json()
        pr=await c.get(GOOGLE_USERINFO,headers={"Authorization":f"Bearer {td['access_token']}"});pr.raise_for_status();profile=pr.json()
    ex=row("SELECT * FROM gmail_accounts WHERE telegram_user_id=:u AND google_subject=:s",u=uid,s=profile["sub"]);refresh=td.get("refresh_token") or (dec(ex["refresh_token_enc"]) if ex else "")
    if not refresh:raise HTTPException(400,"No refresh token returned")
    if ex:execq("UPDATE gmail_accounts SET email=:e,refresh_token_enc=:r,updated_at=:d WHERE id=:i",e=profile["email"].lower(),r=enc(refresh),d=iso(),i=ex["id"])
    else:execq("INSERT INTO gmail_accounts(telegram_user_id,google_subject,email,refresh_token_enc,test_opt_in,test_scope,connected_at,updated_at) VALUES(:u,:s,:e,:r,0,'team',:d,:d)",u=uid,s=profile["sub"],e=profile["email"].lower(),r=enc(refresh),d=iso())
    return HTMLResponse("<h2>Gmail connected.</h2><p>Return to Telegram and use /gmail.</p>")

@app.get("/compose")
async def compose(t:str):
    p=serializer.loads(t,max_age=3600);uid=int(p["uid"]);mid=int(p["mid"]);tm=team(uid)
    m=row("SELECT m.*,COALESCE(NULLIF(m.recipient_email,''),p.email) recipient FROM messages m JOIN prospects p ON p.id=m.prospect_id WHERE m.id=:m AND m.team_id=:t",m=mid,t=tm["id"])
    if not m:raise HTTPException(404)
    params={"view":"cm","fs":"1","to":m["recipient"],"su":m["subject"],"body":m["body"]}
    return RedirectResponse("https://mail.google.com/mail/?"+urlencode(params))


# AUTHOR_SCOUT_V3_BRIDGE
# Keeps older Render start commands working. When bot_main is the entrypoint,
# load the v3 overlay after all legacy definitions are available.
if __name__ != "bot_main_v3":
    try:
        import bot_main_v3 as _author_scout_v3
        app = _author_scout_v3.app
        print("AUTHOR_SCOUT_V3_BRIDGE loaded=True version=" + str(getattr(app, "version", "")))
    except Exception as _v3_error:
        print(f"AUTHOR_SCOUT_V3_BRIDGE loaded=False error={type(_v3_error).__name__}: {_v3_error}")
