from __future__ import annotations
import asyncio, base64, csv, html, io, json, os, random, re, secrets, tempfile
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path
from urllib.parse import urlencode, urljoin, urlparse
from zoneinfo import ZoneInfo

import httpx
from bs4 import BeautifulSoup
from cryptography.fernet import Fernet
from ddgs import DDGS
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse, RedirectResponse, HTMLResponse
from itsdangerous import URLSafeTimedSerializer
from openpyxl import Workbook, load_workbook
from sqlalchemy import create_engine, text

TOKEN=os.getenv("TELEGRAM_BOT_TOKEN","")
BASE=os.getenv("PUBLIC_BASE_URL","").rstrip("/")
WEBHOOK_SECRET=os.getenv("TELEGRAM_WEBHOOK_SECRET","")
DB=os.getenv("DATABASE_URL","sqlite:///./scoutbot.db")
APP_SECRET=os.getenv("APP_SECRET","change-me")
ENC_KEY=os.getenv("TOKEN_ENCRYPTION_KEY","")
GOOGLE_CLIENT_ID=os.getenv("GOOGLE_CLIENT_ID","")
GOOGLE_CLIENT_SECRET=os.getenv("GOOGLE_CLIENT_SECRET","")
GOOGLE_REDIRECT_URI=os.getenv("GOOGLE_REDIRECT_URI","") or (f"{BASE}/oauth/google/callback" if BASE else "")
MAX_FIND=int(os.getenv("MAX_FIND_COUNT","30"))
TIMEOUT=float(os.getenv("REQUEST_TIMEOUT","12"))
TZ=ZoneInfo(os.getenv("TIMEZONE_NAME","Africa/Lagos"))
YEAR=datetime.now(timezone.utc).year

if DB.startswith("postgres://"): DB="postgresql+psycopg://"+DB[len("postgres://"):]
elif DB.startswith("postgresql://"): DB="postgresql+psycopg://"+DB[len("postgresql://"):]

engine=create_engine(DB,pool_pre_ping=True,future=True)
serializer=URLSafeTimedSerializer(APP_SECRET,salt="author-scout")
try:
    fernet=Fernet(ENC_KEY.encode()) if ENC_KEY else None
except Exception:
    fernet=None
TG=f"https://api.telegram.org/bot{TOKEN}"
TGFILE=f"https://api.telegram.org/file/bot{TOKEN}"
EMAIL_RE=re.compile(r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}",re.I)
HEADERS={"User-Agent":"Mozilla/5.0 AuthorScoutTeamBot/2.0"}
SOCIAL={"facebook.com","instagram.com","x.com","twitter.com","linkedin.com","youtube.com","tiktok.com","goodreads.com","amazon.com","wikipedia.org"}
GMAIL_SCOPE="openid email https://www.googleapis.com/auth/gmail.send"
GOOGLE_AUTH="https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN="https://oauth2.googleapis.com/token"
GOOGLE_USERINFO="https://openidconnect.googleapis.com/v1/userinfo"
GMAIL_SEND="https://gmail.googleapis.com/gmail/v1/users/me/messages/send"

app=FastAPI(title="Author Scout Team Bot",version="2.0")

def now(): return datetime.now(timezone.utc)
def iso(dt=None): return (dt or now()).isoformat()
def esc(v): return html.escape(str(v or ""))
def rows(q,**p):
    with engine.begin() as c: return [dict(r._mapping) for r in c.execute(text(q),p)]
def row(q,**p):
    x=rows(q,**p); return x[0] if x else None
def execq(q,**p):
    with engine.begin() as c: c.execute(text(q),p)

def init_db():
    pk="INTEGER PRIMARY KEY AUTOINCREMENT" if DB.startswith("sqlite") else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    stmts=[
      "CREATE TABLE IF NOT EXISTS users(telegram_user_id BIGINT PRIMARY KEY,username TEXT DEFAULT '',first_name TEXT DEFAULT '',team_id INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS teams(id {pk},name TEXT NOT NULL,invite_code TEXT NOT NULL UNIQUE,owner_user_id BIGINT NOT NULL,created_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS prospects(id {pk},normalized_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,country TEXT DEFAULT '',genre TEXT DEFAULT '',website TEXT DEFAULT '',email TEXT DEFAULT '',email_source_url TEXT DEFAULT '',verification_status TEXT DEFAULT 'unverified',bio TEXT DEFAULT '',books TEXT DEFAULT '',recent_activity TEXT DEFAULT '',source_urls TEXT DEFAULT '[]',claimed_team_id INTEGER NOT NULL,claimed_by_user_id BIGINT NOT NULL,claimed_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS messages(id {pk},team_id INTEGER NOT NULL,prospect_id INTEGER NOT NULL,imported_by_user_id BIGINT NOT NULL,subject TEXT DEFAULT '',body TEXT DEFAULT '',status TEXT DEFAULT 'ready',sender_email TEXT DEFAULT '',sent_by_user_id BIGINT,sent_at TEXT DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS sender_emails(id {pk},telegram_user_id BIGINT NOT NULL,email TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(telegram_user_id,email))",
      f"CREATE TABLE IF NOT EXISTS scout_events(id {pk},telegram_user_id BIGINT NOT NULL,team_id INTEGER NOT NULL,prospect_id INTEGER NOT NULL,created_at TEXT NOT NULL)",
      f"CREATE TABLE IF NOT EXISTS gmail_accounts(id {pk},telegram_user_id BIGINT NOT NULL,google_subject TEXT NOT NULL,email TEXT NOT NULL,refresh_token_enc TEXT NOT NULL,test_opt_in INTEGER NOT NULL DEFAULT 0,test_scope TEXT NOT NULL DEFAULT 'team',connected_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(telegram_user_id,google_subject))",
      f"CREATE TABLE IF NOT EXISTS delivery_tests(id {pk},team_id INTEGER NOT NULL,requested_by_user_id BIGINT NOT NULL,message_id INTEGER NOT NULL,sender_gmail_id INTEGER NOT NULL,sender_email TEXT NOT NULL,requested_count INTEGER NOT NULL DEFAULT 10,sent_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'sending',created_at TEXT NOT NULL,completed_at TEXT DEFAULT '')",
      f"CREATE TABLE IF NOT EXISTS delivery_test_recipients(id {pk},test_id INTEGER NOT NULL,gmail_account_id INTEGER NOT NULL,owner_user_id BIGINT NOT NULL,email TEXT NOT NULL,result TEXT NOT NULL DEFAULT 'pending',sent_at TEXT NOT NULL,responded_at TEXT DEFAULT '',UNIQUE(test_id,gmail_account_id))"
    ]
    with engine.begin() as c:
        for s in stmts: c.execute(text(s))

def ensure_user(u):
    uid=int(u["id"]); ex=row("SELECT telegram_user_id FROM users WHERE telegram_user_id=:u",u=uid)
    if not ex: execq("INSERT INTO users(telegram_user_id,username,first_name,created_at,updated_at) VALUES(:u,:n,:f,:t,:t)",u=uid,n=u.get("username",""),f=u.get("first_name",""),t=iso())
    else: execq("UPDATE users SET username=:n,first_name=:f,updated_at=:t WHERE telegram_user_id=:u",u=uid,n=u.get("username",""),f=u.get("first_name",""),t=iso())
    return uid

def team(uid):
    return row("SELECT t.* FROM users u JOIN teams t ON t.id=u.team_id WHERE u.telegram_user_id=:u",u=uid)

def invite():
    alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    for _ in range(50):
        c="".join(secrets.choice(alphabet) for _ in range(7))
        if not row("SELECT id FROM teams WHERE invite_code=:c",c=c): return c
    raise RuntimeError("Could not create code")

def pkey(d):
    if d.get("email"): return "email:"+d["email"].lower().strip()
    if d.get("website"):
        try:
            p=urlparse(d["website"] if "://" in d["website"] else "https://"+d["website"])
            return "site:"+p.netloc.lower().replace("www.","")+p.path.rstrip("/")
        except: pass
    return "name:"+re.sub("[^a-z0-9]","",(d.get("name") or "").lower())+":"+re.sub("[^a-z0-9]","",(d.get("country") or "").lower())

def claim(uid,tid,d):
    k=pkey(d); ex=row("SELECT * FROM prospects WHERE normalized_key=:k",k=k)
    if ex: return ex["id"],False,ex
    vals={"k":k,"n":d.get("name",""),"c":d.get("country",""),"g":d.get("genre",""),"w":d.get("website",""),"e":(d.get("email") or "").lower(),"es":d.get("email_source_url",""),"v":d.get("verification_status","unverified"),"b":d.get("bio",""),"bk":d.get("books",""),"a":d.get("recent_activity",""),"s":json.dumps(d.get("source_urls",[])),"tid":tid,"uid":uid,"t":iso()}
    try:
        with engine.begin() as c:
            r=c.execute(text("INSERT INTO prospects(normalized_key,name,country,genre,website,email,email_source_url,verification_status,bio,books,recent_activity,source_urls,claimed_team_id,claimed_by_user_id,claimed_at,updated_at) VALUES(:k,:n,:c,:g,:w,:e,:es,:v,:b,:bk,:a,:s,:tid,:uid,:t,:t) RETURNING id"),vals)
            pid=int(r.scalar_one())
            c.execute(text("INSERT INTO scout_events(telegram_user_id,team_id,prospect_id,created_at) VALUES(:uid,:tid,:pid,:t)"),{"uid":uid,"tid":tid,"pid":pid,"t":vals["t"]})
        return pid,True,None
    except Exception:
        ex=row("SELECT * FROM prospects WHERE normalized_key=:k",k=k)
        return (ex["id"],False,ex) if ex else (0,False,None)

async def tg(method,data=None,files=None):
    async with httpx.AsyncClient(timeout=60) as c:
        r=await c.post(f"{TG}/{method}",data=data,files=files); r.raise_for_status(); j=r.json()
        if not j.get("ok"): raise RuntimeError(j)
        return j.get("result")
async def send(chat,msg,kb=None):
    d={"chat_id":str(chat),"text":msg,"parse_mode":"HTML","disable_web_page_preview":"true"}
    if kb: d["reply_markup"]=json.dumps(kb)
    return await tg("sendMessage",d)
async def send_doc(chat,path,cap=""):
    with open(path,"rb") as f: return await tg("sendDocument",{"chat_id":str(chat),"caption":cap},{"document":(Path(path).name,f)})

def ddgs(q,n=10):
    out=[]
    try:
        with DDGS(timeout=max(5,int(TIMEOUT))) as d:
            for x in d.text(q,max_results=n,safesearch="moderate"):
                out.append({"title":x.get("title",""),"url":x.get("href") or x.get("url",""),"snippet":x.get("body") or x.get("snippet","")})
    except: pass
    return out
async def search(q,n=10): return await asyncio.to_thread(ddgs,q,n)

def cand(title,snip=""):
    t=re.sub(r"\b(official site|official website|author|writer|books|home)\b","",title,flags=re.I)
    for sep in [" | "," – "," — "," - ",": "]:
        if sep in t: t=t.split(sep)[0]
    t=re.sub(r"\s+"," ",t).strip(" -|:,.")
    if 2<=len(t.split())<=5 and len(t)<80:return t
    m=re.search(r"\b([A-Z][a-zÀ-ÿ'’-]+(?:\s+[A-Z][a-zÀ-ÿ'’-]+){1,3})\b",snip); return m.group(1) if m else ""

def host(u):
    try:return urlparse(u).netloc.lower().replace("www.","")
    except:return ""
def official(u,n):
    h=host(u)
    if not h or any(h==s or h.endswith("."+s) for s in SOCIAL):return False
    compact=re.sub("[^a-z]","",h)
    return any(re.sub("[^a-z]","",x.lower()) in compact for x in n.split() if len(x)>2)
async def fetch(u):
    try:
        async with httpx.AsyncClient(timeout=TIMEOUT,headers=HEADERS,follow_redirects=True) as c:
            r=await c.get(u)
            if r.status_code>=400 or "text/html" not in r.headers.get("content-type",""):return "",u
            return r.text[:1000000],str(r.url)
    except:return "",u
def emails(raw):
    s=BeautifulSoup(raw,"html.parser"); vals=EMAIL_RE.findall(s.get_text(" "))
    for a in s.select('a[href^="mailto:"]'): vals+=EMAIL_RE.findall(a.get("href",""))
    bad={"support","sales","admin","privacy","legal","noreply","no-reply"}; out=[]
    for e in vals:
        e=e.lower().strip(".,;:()[]<>")
        if e.split("@")[0] not in bad and e not in out: out.append(e)
    return out

async def research(name,country="",genre="",hint=""):
    rs=await search(f'"{name}" author official website',8)
    if hint:rs=[{"title":"hint","url":hint,"snippet":""}]+rs
    website=next((r["url"] for r in rs if official(r["url"],name)), "")
    if not website: website=next((r["url"] for r in rs if r["url"] and not any(x in host(r["url"]) for x in ["amazon.","goodreads.","wikipedia."])), "")
    bio=emailv=source=""; sources=[]; verified="unverified"
    if website:
        raw,final=await fetch(website); sources.append(final); s=BeautifulSoup(raw,"html.parser")
        bio=re.sub(r"\s+"," ",s.get_text(" ")).strip()[:700]; em=emails(raw)
        if em: emailv=em[0]; source=final; verified="verified_public"
        if not emailv:
            for a in s.find_all("a",href=True):
                label=(a.get_text(" ")+" "+a["href"]).lower()
                if "contact" in label:
                    u=urljoin(final,a["href"])
                    if host(u)==host(final):
                        rr,ff=await fetch(u); em=emails(rr); sources.append(ff)
                        if em: emailv=em[0]; source=ff; verified="verified_public"; break
    act=await search(f'"{name}" author {YEAR} book OR event OR release',3)
    activity=(act[0]["title"]+": "+act[0]["snippet"])[:700] if act else ""
    if act and act[0]["url"]:sources.append(act[0]["url"])
    return {"name":name,"country":country,"genre":genre,"website":website,"email":emailv,"email_source_url":source,"verification_status":verified,"bio":bio,"books":"","recent_activity":activity,"source_urls":list(dict.fromkeys(sources))}

async def find_authors(country,genre,gender,count,require_email):
    extra=(f' "{genre}"' if genre else "")+(" male" if gender=="male" else " female" if gender=="female" else "")
    seen=set(); cands=[]
    for q in [f'"{country}" author{extra} official website books',f'"{country}" writer{extra} contact author',f'"{country}" author{extra} {YEAR} new book']:
        for r in await search(q,max(12,count)):
            n=cand(r["title"],r["snippet"]); k=re.sub("[^a-z0-9]","",n.lower())
            if n and k not in seen:seen.add(k);cands.append((n,r["url"]))
    out=[]
    for n,h in cands[:max(count*4,20)]:
        d=await research(n,country,genre,h)
        if require_email and not d["email"]:continue
        out.append(d)
        if len(out)>=count:break
    return out

def parse_find(a):
    p=[x.strip() for x in a.split("|")]; n=10
    try:n=int(p[0]);p=p[1:]
    except:pass
    return min(max(n,1),MAX_FIND),p[0] if p else "any country",p[1] if len(p)>1 else "",p[2].lower() if len(p)>2 else "any",not(len(p)>3 and p[3].lower() in {"optional","no","noemail"})

def enc(v):
    if not fernet:raise RuntimeError("TOKEN_ENCRYPTION_KEY missing")
    return fernet.encrypt(v.encode()).decode()
def dec(v):
    if not fernet:raise RuntimeError("TOKEN_ENCRYPTION_KEY missing")
    return fernet.decrypt(v.encode()).decode()
def gmail_ok():return all([GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI,BASE,ENC_KEY])
async def access(refresh):
    async with httpx.AsyncClient(timeout=30) as c:
        r=await c.post(GOOGLE_TOKEN,data={"client_id":GOOGLE_CLIENT_ID,"client_secret":GOOGLE_CLIENT_SECRET,"refresh_token":refresh,"grant_type":"refresh_token"});r.raise_for_status();return r.json()["access_token"]
async def gmail_send(account,to,subject,body):
    token=await access(dec(account["refresh_token_enc"])); m=EmailMessage();m["To"]=to;m["From"]=account["email"];m["Subject"]=subject;m.set_content(body)
    raw=base64.urlsafe_b64encode(m.as_bytes()).decode().rstrip("=")
    async with httpx.AsyncClient(timeout=30) as c:
        r=await c.post(GMAIL_SEND,headers={"Authorization":f"Bearer {token}"},json={"raw":raw});r.raise_for_status();return r.json()

async def live_test(chat,uid,mid,gid):
    t=team(uid)
    m=row("SELECT m.*,p.name,p.email FROM messages m JOIN prospects p ON p.id=m.prospect_id WHERE m.id=:m AND m.team_id=:t",m=mid,t=t["id"])
    sender=row("SELECT * FROM gmail_accounts WHERE id=:g AND telegram_user_id=:u",g=gid,u=uid)
    if not m or not sender: return await send(chat,"Message or Gmail account not found.")
    pool=rows("""SELECT g.*,u.team_id FROM gmail_accounts g JOIN users u ON u.telegram_user_id=g.telegram_user_id
      WHERE g.test_opt_in=1 AND lower(g.email)<>:e AND (g.test_scope='global' OR u.team_id=:t)""",e=sender["email"].lower(),t=t["id"])
    random.shuffle(pool); pool=pool[:10]
    if not pool:return await send(chat,"No opted-in test inboxes are available yet.")
    with engine.begin() as c:
        r=c.execute(text("INSERT INTO delivery_tests(team_id,requested_by_user_id,message_id,sender_gmail_id,sender_email,requested_count,sent_count,status,created_at) VALUES(:t,:u,:m,:g,:e,10,0,'sending',:d) RETURNING id"),{"t":t["id"],"u":uid,"m":mid,"g":gid,"e":sender["email"],"d":iso()});test_id=int(r.scalar_one())
    sent=0
    for a in pool:
        try:
            await gmail_send(sender,a["email"],"[Deliverability Test] "+m["subject"],m["body"])
            execq("INSERT INTO delivery_test_recipients(test_id,gmail_account_id,owner_user_id,email,result,sent_at) VALUES(:t,:g,:u,:e,'pending',:d)",t=test_id,g=a["id"],u=a["telegram_user_id"],e=a["email"],d=iso());sent+=1
            kb={"inline_keyboard":[[{"text":"Inbox","callback_data":f"place:{test_id}:{a['id']}:inbox"},{"text":"Spam","callback_data":f"place:{test_id}:{a['id']}:spam"}],[{"text":"Promotions","callback_data":f"place:{test_id}:{a['id']}:promotions"},{"text":"Not received","callback_data":f"place:{test_id}:{a['id']}:not_received"}]]}
            await send(a["telegram_user_id"],f"🧪 <b>Deliverability test</b>\nCheck <code>{esc(a['email'])}</code> for a message from <code>{esc(sender['email'])}</code>, then report where it landed.",kb)
        except Exception:pass
    execq("UPDATE delivery_tests SET sent_count=:s,status='waiting' WHERE id=:i",s=sent,i=test_id)
    await send(chat,f"🧪 Test #{test_id} sent to <b>{sent}</b> opted-in inboxes.\nUse /deliverytests to see reports.")

def test_report(test_id):
    rs=rows("SELECT result,COUNT(*) c FROM delivery_test_recipients WHERE test_id=:i GROUP BY result",i=test_id)
    d={r["result"]:r["c"] for r in rs}; total=sum(d.values())
    return total,d

async def cmd_stats(chat,uid,arg=""):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    n=now().astimezone(TZ); start=n.replace(hour=0,minute=0,second=0,microsecond=0).astimezone(timezone.utc)
    y=start-timedelta(days=1); seven=start-timedelta(days=6)
    def count(s,e):return int((row("SELECT COUNT(*) c FROM scout_events WHERE team_id=:t AND created_at>=:s AND created_at<:e",t=t["id"],s=iso(s),e=iso(e)) or {"c":0})["c"])
    today=count(start,now()+timedelta(seconds=1)); yesterday=count(y,start); last7=count(seven,now()+timedelta(seconds=1))
    def leader(s,e):
        return row("""SELECT u.first_name,u.username,COUNT(*) c FROM scout_events x JOIN users u ON u.telegram_user_id=x.telegram_user_id
          WHERE x.created_at>=:s AND x.created_at<:e GROUP BY x.telegram_user_id,u.first_name,u.username ORDER BY c DESC LIMIT 1""",s=iso(s),e=iso(e))
    ld=leader(start,now()+timedelta(seconds=1)); l5=leader(now()-timedelta(hours=5),now()+timedelta(seconds=1))
    name=lambda r:(r["first_name"] or ("@"+r["username"] if r.get("username") else "Unknown")) if r else "No scout"
    custom=""
    if arg:
        p=arg.split()
        if len(p)==2:
            try:
                s=datetime.strptime(p[0],"%Y-%m-%d").replace(tzinfo=TZ).astimezone(timezone.utc);e=datetime.strptime(p[1],"%Y-%m-%d").replace(tzinfo=TZ).astimezone(timezone.utc)+timedelta(days=1)
                custom=f"\nSelected range: <b>{count(s,e)}</b>"
            except:custom="\nUse /stats YYYY-MM-DD YYYY-MM-DD"
    await send(chat,f"<b>{esc(t['name'])} stats</b>\nToday: <b>{today}</b>\nYesterday: <b>{yesterday}</b>\nLast 7 days: <b>{last7}</b>{custom}\n\n🏆 Today: <b>{esc(name(ld))}</b> ({ld['c'] if ld else 0})\n🔥 Last 5 hours: <b>{esc(name(l5))}</b> ({l5['c'] if l5 else 0})")

async def import_sheet(chat,uid,doc):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    info=await tg("getFile",{"file_id":doc["file_id"]}); ext=Path(doc.get("file_name") or "x.xlsx").suffix.lower()
    async with httpx.AsyncClient(timeout=60) as c:r=await c.get(f"{TGFILE}/{info['file_path']}");data=r.content
    table=list(csv.reader(io.StringIO(data.decode("utf-8-sig")))) if ext==".csv" else [list(x) for x in load_workbook(io.BytesIO(data),read_only=True,data_only=True).active.iter_rows(values_only=True)]
    h=[str(x or "").strip().lower() for x in table[0]]
    def ix(names):
        for n in names:
            if n in h:return h.index(n)
    ia,ie,isub,ib=ix(["author","author name","name"]),ix(["email","author email"]),ix(["subject","subject line"]),ix(["first message","message","body","email body"])
    if isub is None or ib is None:return await send(chat,"Need Author/Email, Subject and First Message columns.")
    ps=rows("SELECT * FROM prospects WHERE claimed_team_id=:t",t=t["id"]);bn={p["name"].lower():p for p in ps};be={p["email"].lower():p for p in ps if p["email"]};matched=0
    for r in table[1:]:
        g=lambda i:str(r[i] or "").strip() if i is not None and i<len(r) else ""
        p=be.get(g(ie).lower()) if ie is not None else None
        if not p and ia is not None:p=bn.get(g(ia).lower())
        if not p:continue
        ex=row("SELECT id,status FROM messages WHERE team_id=:t AND prospect_id=:p ORDER BY id DESC LIMIT 1",t=t["id"],p=p["id"])
        if ex:execq("UPDATE messages SET subject=:s,body=:b,status=CASE WHEN status='sent' THEN status ELSE 'ready' END,updated_at=:d WHERE id=:i",s=g(isub),b=g(ib),d=iso(),i=ex["id"])
        else:execq("INSERT INTO messages(team_id,prospect_id,imported_by_user_id,subject,body,status,created_at,updated_at) VALUES(:t,:p,:u,:s,:b,'ready',:d,:d)",t=t["id"],p=p["id"],u=uid,s=g(isub),b=g(ib),d=iso())
        matched+=1
    await send(chat,f"✅ Imported {matched} message(s). Use /queue.")

async def queue(chat,uid,skip=None):
    t=team(uid)
    if not t:return await send(chat,"Join/create a team first.")
    q=rows("SELECT m.*,p.name,p.email FROM messages m JOIN prospects p ON p.id=m.prospect_id WHERE m.team_id=:t AND m.status='ready' ORDER BY m.id",t=t["id"])
    if skip:q=[x for x in q if x["id"]!=skip]+[x for x in q if x["id"]==skip]
    if not q:return await send(chat,"No unsent messages.")
    m=q[0]; token=serializer.dumps({"uid":uid,"mid":m["id"]});url=f"{BASE}/compose?t={token}" if BASE else "https://mail.google.com/"
    kb={"inline_keyboard":[[{"text":"📨 Open Gmail","url":url},{"text":"✅ Mark Sent","callback_data":f"sent:{m['id']}"}],[{"text":"🧪 Live Deliverability Test","callback_data":f"test:{m['id']}"},{"text":"⏭ Skip","callback_data":f"skip:{m['id']}"}]]}
    await send(chat,f"<b>{esc(m['name'])}</b>\nTo: <code>{esc(m['email'])}</code>\n\n<b>Subject</b>\n{esc(m['subject'])}\n\n<b>Message</b>\n{esc(m['body'])}\n\n{len(q)} unsent",kb)

HELP="""<b>Author Scout Team Bot</b>
/newteam Team Name
/join CODE
/team
/find 10 | UAE | fiction | male | email
/research Author Name
/authors
/export
/brief
/queue
/gmail
/deliverytests
/stats
/stats 2026-09-01 2026-09-15
/leaderboard

Upload ChatGPT XLSX/CSV directly to import messages.
The same prospect cannot be claimed twice anywhere in the bot."""

async def handle(up):
    if up.get("callback_query"):
        cb=up["callback_query"];uid=ensure_user(cb["from"]);chat=cb["message"]["chat"]["id"];await tg("answerCallbackQuery",{"callback_query_id":cb["id"]});d=cb.get("data","");t=team(uid)
        if d.startswith("sent:") and t:
            mid=int(d.split(":")[1]);execq("UPDATE messages SET status='sent',sent_by_user_id=:u,sent_at=:d,updated_at=:d WHERE id=:m AND team_id=:t",u=uid,d=iso(),m=mid,t=t["id"]);return await queue(chat,uid)
        if d.startswith("skip:"):return await queue(chat,uid,int(d.split(":")[1]))
        if d.startswith("test:") and t:
            mid=int(d.split(":")[1]);acs=rows("SELECT id,email FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id",u=uid)
            if not acs:return await send(chat,"Connect Gmail first with /gmail.")
            kb={"inline_keyboard":[[{"text":a["email"],"callback_data":f"run:{mid}:{a['id']}"}] for a in acs]};return await send(chat,"Choose the Gmail sender for this live test:",kb)
        if d.startswith("run:"):
            _,mid,gid=d.split(":");return await live_test(chat,uid,int(mid),int(gid))
        if d.startswith("place:"):
            _,tid,gid,res=d.split(":");a=row("SELECT * FROM gmail_accounts WHERE id=:g AND telegram_user_id=:u",g=int(gid),u=uid)
            if a:
                execq("UPDATE delivery_test_recipients SET result=:r,responded_at=:d WHERE test_id=:t AND gmail_account_id=:g",r=res,d=iso(),t=int(tid),g=int(gid))
                total,stats=test_report(int(tid));test=row("SELECT requested_by_user_id FROM delivery_tests WHERE id=:i",i=int(tid))
                await send(chat,"✅ Placement recorded.")
                if test:await send(test["requested_by_user_id"],f"🧪 Test #{tid} update\nInbox: {stats.get('inbox',0)}\nPromotions: {stats.get('promotions',0)}\nSpam: {stats.get('spam',0)}\nNot received: {stats.get('not_received',0)}\nPending: {stats.get('pending',0)}")
            return
        if d.startswith("opt:"):
            _,gid,scope=d.split(":");execq("UPDATE gmail_accounts SET test_opt_in=1,test_scope=:s,updated_at=:d WHERE id=:g AND telegram_user_id=:u",s=scope,d=iso(),g=int(gid),u=uid);return await send(chat,f"✅ Test inbox enabled ({scope}).")
        if d.startswith("off:"):
            gid=int(d.split(":")[1]);execq("UPDATE gmail_accounts SET test_opt_in=0,updated_at=:d WHERE id=:g AND telegram_user_id=:u",d=iso(),g=gid,u=uid);return await send(chat,"✅ Test inbox disabled.")
        return
    m=up.get("message") or {};u=m.get("from") or {};uid=u.get("id");chat=(m.get("chat") or {}).get("id")
    if not uid or not chat:return
    uid=ensure_user(u);t=team(uid)
    if m.get("document"):return await import_sheet(chat,uid,m["document"])
    txt=m.get("text") or "";parts=txt.split(maxsplit=1);cmd=parts[0].split("@")[0].lower() if txt.startswith("/") else "";arg=parts[1] if len(parts)>1 else ""
    if cmd in {"/start","/help"}:return await send(chat,HELP)
    if cmd=="/newteam":
        if t:return await send(chat,"You are already in a team.")
        if not arg:return await send(chat,"Use /newteam Team Name")
        code=invite()
        with engine.begin() as c:
            r=c.execute(text("INSERT INTO teams(name,invite_code,owner_user_id,created_at) VALUES(:n,:c,:u,:d) RETURNING id"),{"n":arg,"c":code,"u":uid,"d":iso()});tid=int(r.scalar_one());c.execute(text("UPDATE users SET team_id=:t,updated_at=:d WHERE telegram_user_id=:u"),{"t":tid,"d":iso(),"u":uid})
        return await send(chat,f"✅ Team created. Invite code: <code>{code}</code>")
    if cmd=="/join":
        if t:return await send(chat,"You are already in a team.")
        x=row("SELECT * FROM teams WHERE invite_code=:c",c=arg.strip().upper())
        if not x:return await send(chat,"Invalid invite code.")
        execq("UPDATE users SET team_id=:t,updated_at=:d WHERE telegram_user_id=:u",t=x["id"],d=iso(),u=uid);return await send(chat,f"✅ Joined <b>{esc(x['name'])}</b>.")
    if cmd=="/team":
        t=team(uid);return await send(chat,f"<b>{esc(t['name'])}</b>\nInvite: <code>{t['invite_code']}</code>" if t else "No team.")
    if cmd=="/find":
        t=team(uid)
        if not t:return await send(chat,"Join/create a team first.")
        n,c,g,gender,req=parse_find(arg);await send(chat,f"🔎 Scouting up to {n} new authors in {esc(c)}…");found=await find_authors(c,g,gender,max(n*2,n),req);new=dup=0
        for d in found:
            _,created,_=claim(uid,t["id"],d);new+=int(created);dup+=int(not created)
            if new>=n:break
        return await send(chat,f"✅ New claimed: <b>{new}</b>\nDuplicates blocked: <b>{dup}</b>")
    if cmd=="/research":
        t=team(uid)
        if not t:return await send(chat,"Join/create a team first.")
        d=await research(arg);pid,created,ex=claim(uid,t["id"],d)
        return await send(chat,f"✅ Claimed {esc(d['name'])}" if created else f"⚠️ Already scouted: {esc(ex['name'])}")
    if cmd=="/authors":
        t=team(uid);ps=rows("SELECT * FROM prospects WHERE claimed_team_id=:t ORDER BY id DESC LIMIT 30",t=t["id"]) if t else []
        return await send(chat,"\n".join([f"• {esc(p['name'])} — {esc(p['email'] or 'no email')}" for p in ps]) or "No authors.")
    if cmd=="/stats":return await cmd_stats(chat,uid,arg)
    if cmd=="/leaderboard":
        s=now().astimezone(TZ).replace(hour=0,minute=0,second=0,microsecond=0).astimezone(timezone.utc);ls=rows("SELECT u.first_name,u.username,COUNT(*) c FROM scout_events x JOIN users u ON u.telegram_user_id=x.telegram_user_id WHERE x.created_at>=:s GROUP BY x.telegram_user_id,u.first_name,u.username ORDER BY c DESC LIMIT 10",s=iso(s));return await send(chat,"<b>🏆 Today</b>\n"+"\n".join([f"{i+1}. {esc(r['first_name'] or '@'+r['username'])} — {r['c']}" for i,r in enumerate(ls)]))
    if cmd=="/queue":return await queue(chat,uid)
    if cmd=="/gmail":
        acs=rows("SELECT * FROM gmail_accounts WHERE telegram_user_id=:u ORDER BY id",u=uid);lines=["<b>Gmail / test inboxes</b>"]+[f"• {esc(a['email'])} — {'ON '+a['test_scope'] if a['test_opt_in'] else 'OFF'}" for a in acs]
        kb={"inline_keyboard":[]}
        if gmail_ok():kb["inline_keyboard"].append([{"text":"➕ Connect Gmail","url":f"{BASE}/oauth/google/start?t="+serializer.dumps({'uid':uid})}])
        for a in acs:kb["inline_keyboard"] += [[{"text":"Team pool","callback_data":f"opt:{a['id']}:team"},{"text":"Global pool","callback_data":f"opt:{a['id']}:global"},{"text":"Off","callback_data":f"off:{a['id']}"}]]
        return await send(chat,"\n".join(lines),kb if kb["inline_keyboard"] else None)
    if cmd=="/deliverytests":
        ts=rows("SELECT * FROM delivery_tests WHERE requested_by_user_id=:u ORDER BY id DESC LIMIT 10",u=uid);out=["<b>Your tests</b>"]
        for x in ts:
            total,st=test_report(x["id"]);out.append(f"#{x['id']} — sent {x['sent_count']} — inbox {st.get('inbox',0)} / spam {st.get('spam',0)} / promotions {st.get('promotions',0)} / pending {st.get('pending',0)}")
        return await send(chat,"\n".join(out))
    return await send(chat,"Use /help.")

@app.on_event("startup")
async def startup():
    raw_db=os.getenv("DATABASE_URL","")
    try:
        p=urlparse(raw_db if raw_db else "sqlite:///./scoutbot.db")
        print(f"DB_DIAGNOSTIC configured={bool(raw_db)} scheme={p.scheme or 'sqlite'} host={p.hostname or ''} database={(p.path or '').lstrip('/') or 'scoutbot.db'}")
    except Exception:
        print(f"DB_DIAGNOSTIC configured={bool(raw_db)} scheme=unknown host= database=")
    init_db()
    if TOKEN and BASE and WEBHOOK_SECRET:
        try:
            await tg("setWebhook",{"url":f"{BASE}/telegram/webhook","secret_token":WEBHOOK_SECRET})
        except Exception as e: print(e)

@app.get("/")
async def root():return {"ok":True,"name":"Author Scout Team Bot","version":"2.0"}
@app.get("/health")
async def health():return {"ok":True}

@app.get("/debug/db")
async def debug_db():
    raw=os.getenv("DATABASE_URL","")
    try:
        p=urlparse(raw if raw else "sqlite:///./scoutbot.db")
        return {
            "configured": bool(raw),
            "scheme": p.scheme or "sqlite",
            "host": p.hostname or "",
            "database": (p.path or "").lstrip("/") or "scoutbot.db"
        }
    except Exception:
        return {"configured": bool(raw), "scheme": "unknown", "host": "", "database": ""}
@app.post("/telegram/webhook")
async def webhook(request:Request,x_telegram_bot_api_secret_token:str|None=Header(default=None)):
    if x_telegram_bot_api_secret_token!=WEBHOOK_SECRET:raise HTTPException(403)
    asyncio.create_task(handle(await request.json()));return {"ok":True}

@app.get("/oauth/google/start")
async def oauth_start(t:str):
    if not gmail_ok():raise HTTPException(503,"Gmail OAuth not configured")
    p=serializer.loads(t,max_age=900);state=serializer.dumps({"uid":int(p["uid"])})
    return RedirectResponse(GOOGLE_AUTH+"?"+urlencode({"client_id":GOOGLE_CLIENT_ID,"redirect_uri":GOOGLE_REDIRECT_URI,"response_type":"code","scope":GMAIL_SCOPE,"access_type":"offline","prompt":"consent","state":state}))

@app.get("/oauth/google/callback")
async def oauth_callback(code:str,state:str,error:str=""):
    if error:return HTMLResponse("Gmail connection cancelled.",400)
    p=serializer.loads(state,max_age=900);uid=int(p["uid"])
    async with httpx.AsyncClient(timeout=30) as c:
        tr=await c.post(GOOGLE_TOKEN,data={"client_id":GOOGLE_CLIENT_ID,"client_secret":GOOGLE_CLIENT_SECRET,"code":code,"grant_type":"authorization_code","redirect_uri":GOOGLE_REDIRECT_URI});tr.raise_for_status();td=tr.json()
        pr=await c.get(GOOGLE_USERINFO,headers={"Authorization":f"Bearer {td['access_token']}"});pr.raise_for_status();profile=pr.json()
    ex=row("SELECT * FROM gmail_accounts WHERE telegram_user_id=:u AND google_subject=:s",u=uid,s=profile["sub"]);refresh=td.get("refresh_token") or (dec(ex["refresh_token_enc"]) if ex else "")
    if not refresh:raise HTTPException(400,"No refresh token returned")
    if ex:execq("UPDATE gmail_accounts SET email=:e,refresh_token_enc=:r,updated_at=:d WHERE id=:i",e=profile["email"].lower(),r=enc(refresh),d=iso(),i=ex["id"])
    else:execq("INSERT INTO gmail_accounts(telegram_user_id,google_subject,email,refresh_token_enc,test_opt_in,test_scope,connected_at,updated_at) VALUES(:u,:s,:e,:r,0,'team',:d,:d)",u=uid,s=profile["sub"],e=profile["email"].lower(),r=enc(refresh),d=iso())
    return HTMLResponse("<h2>Gmail connected.</h2><p>Return to Telegram and use /gmail.</p>")

@app.get("/compose")
async def compose(t:str):
    p=serializer.loads(t,max_age=3600);uid=int(p["uid"]);mid=int(p["mid"]);tm=team(uid)
    m=row("SELECT m.*,p.email recipient FROM messages m JOIN prospects p ON p.id=m.prospect_id WHERE m.id=:m AND m.team_id=:t",m=mid,t=tm["id"])
    if not m:raise HTTPException(404)
    params={"view":"cm","fs":"1","to":m["recipient"],"su":m["subject"],"body":m["body"]}
    return RedirectResponse("https://mail.google.com/mail/?"+urlencode(params))
