import React, {useState,useEffect,useCallback,useRef} from 'react'
import './letterdesk.css'
const initial=m=>Object.fromEntries(['recipient','subject','body','body_english','reply_notes'].map(k=>[k,m[k]||'']))
const state=m=>m.reply_status==='replied'?'replied':m.status
const safeURL=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:null}catch{return null}}
export default function Letterdesk({keyValue,active,request,apiBase}){
 const [items,setItems]=useState([]),[filter,setFilter]=useState('ready'),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[lang,setLang]=useState('body'),[dirty,setDirty]=useState(false),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[gmail,setGmail]=useState({connected:false,accounts:[]}),[sender,setSender]=useState(''),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[report,setReport]=useState(null),[showImport,setShowImport]=useState(false),[mobile,setMobile]=useState(false)
 const input=useRef(null),serial=useRef(0)
 const load=useCallback(async()=>{const n=++serial.current;setLoading(true);try{const d=await request(`/api/v1/messages?status=${filter}&search=${encodeURIComponent(search)}&limit=100&offset=${offset}`,keyValue);if(n!==serial.current)return;setItems(d.messages||[]);setGmail(d.gmail||{connected:false,accounts:[]});setError('')}catch(e){if(n===serial.current)setError(e.message)}finally{if(n===serial.current)setLoading(false)}},[keyValue,filter,search,offset,request])
 useEffect(()=>{if(!active)return;const t=setTimeout(load,250);return()=>{clearTimeout(t);serial.current++}},[active,load])
 useEffect(()=>{const f=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty])
 function choose(m){if(busy||(dirty&&!confirm('Discard unsaved draft changes?')))return;setSelected(m);setDraft(initial(m));setDirty(false);setReviewed(false);setLang('body');setMobile(true);setNotice('')}
 function edit(k,v){setDraft(d=>({...d,[k]:v}));setDirty(true);if(k!=='reply_notes')setReviewed(false)}
 async function save(){setBusy(true);setError('');try{const d=await request(`/api/v1/messages/${selected.id}`,keyValue,{method:'PUT',body:JSON.stringify(draft)});setSelected(d.message);setDraft(initial(d.message));setItems(v=>v.map(m=>m.id===d.message.id?d.message:m));setDirty(false);setNotice('Saved in your workspace.');return true}catch(e){setError(e.message);return false}finally{setBusy(false)}}
 async function upload(f,commit=false){if(!f)return;if(f.size>15*1024*1024){setError('Choose a file under 15 MB.');return}setBusy(true);setError('');setShowImport(true);if(!commit){setFile(f);setPreview(null);setReport(null)}try{const form=new FormData();form.append('file',f);const r=await fetch(apiBase+'/api/v1/messages/import'+(commit?'':'?preview=true'),{method:'POST',headers:{'X-Author-Scout-Key':keyValue},body:form});const d=await r.json();if(!r.ok)throw Error(d.detail||'Import failed');if(commit){setReport(d);setPreview(null);setFile(null);setSelected(null);setDraft(null);setDirty(false);setFilter('ready');setSearch('');setOffset(0);setNotice(`${d.ready} drafts saved. ${d.created} new authors added. ${d.skipped} rows skipped.`);await load()}else setPreview(d)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function download(text,name){const u=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 function template(){download('Author,Email,Website,Subject,First Message,First Message (English),Country,Genre,Email Source URL\r\n','Letterdesk_Import_Template.csv')}
 function issuesCSV(r){const q=v=>'"'+String(v||'').replaceAll('"','""')+'"';download('Row,Author,Reason\r\n'+r.issues.map(i=>[i.row,i.name,i.reason].map(q).join(',')).join('\r\n'),'Letterdesk_Import_Report.csv')}
 const locked=selected&&(['sent','sending','sending_web'].includes(selected.status)||selected.reply_status==='replied'),body=draft?.[lang]||''
 const canSend=!!draft&&/^[^\s@<>;,]+@[^\s@<>;,]+\.[^\s@<>;,]+$/.test(draft.recipient)&&!!draft.subject.trim()&&!!body.trim()&&reviewed&&!busy&&!locked
 function compose(mode){if(mode==='gmail')window.open('https://mail.google.com/mail/?'+new URLSearchParams({view:'cm',fs:'1',to:draft.recipient,su:draft.subject,body}),'_blank','noopener,noreferrer');else window.location.href=`mailto:${encodeURIComponent(draft.recipient)}?subject=${encodeURIComponent(draft.subject)}&body=${encodeURIComponent(body)}`;setNotice('Finish sending in your email app, then mark this message as sent here.')}
 async function mark(next){if(dirty&&!await save())return;setBusy(true);setError('');try{const d=await request(`/api/v1/messages/${selected.id}/status`,keyValue,{method:'POST',body:JSON.stringify({status:next})});setSelected(d.message);setDraft(initial(d.message));setReviewed(false);setNotice('Marked '+next+'.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function send(){if(!confirm(`Send this exact ${lang==='body'?'primary':'English'} message to ${draft.recipient} through your connected Gmail account?`))return;if(dirty&&!await save())return;setBusy(true);try{await request(`/api/v1/messages/${selected.id}/send`,keyValue,{method:'POST',body:JSON.stringify({gmail_id:Number(sender)||0,language:lang})});setSelected(null);setDraft(null);setNotice('Email sent through Gmail.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="ld"><header className="ld-heading"><div><div className="eyebrow">AUTHOR SCOUT / OUTREACH</div><h1>Letterdesk<span>•</span></h1><p>Good research. Thoughtful conversations.</p></div><div className="ld-actions"><button className="ld-btn" onClick={template}>↓ Import template</button><button className="ld-btn ld-primary" disabled={busy||dirty} onClick={()=>input.current.click()}>↑ Upload authors & messages</button><input ref={input} hidden type="file" accept=".xlsx,.xlsm,.csv" onChange={e=>{const f=e.target.files?.[0];e.target.value='';upload(f)}}/></div></header>
 <div className="ld-workflow"><span><b>01</b> Research authors</span><i>→</i><span><b>02</b> Import your workbook</span><i>→</i><span className="current"><b>03</b> Start a conversation</span></div>
 {error&&<div className="ld-alert ld-error" role="alert">{error}</div>}{notice&&<div className="ld-alert" role="status">{notice}</div>}
 {showImport&&<section className="ld-import"><div className="ld-section-head"><div><h2>{report?'Import complete':preview?'Review your import':busy?'Reading workbook…':'Choose another workbook'}</h2><p>{file?.name||report?.sheet}</p></div><button className="ld-btn" disabled={busy} onClick={()=>setShowImport(false)}>Close</button></div>{preview&&<><p><strong>{preview.eligible} eligible rows</strong> · {preview.skipped} skipped · Sheet: {preview.sheet}</p><p className="ld-help">New authors are added to My Authors. Existing unsent drafts may be updated. Sent conversations are preserved.</p><div className="ld-preview-table"><table><thead><tr><th>Author</th><th>Email</th><th>Subject</th><th>Action</th></tr></thead><tbody>{preview.preview.map(r=><tr key={r.row}><td>{r.name}</td><td>{r.email}</td><td>{r.subject}</td><td>{r.action}</td></tr>)}</tbody></table></div><div className="ld-actions"><button className="ld-btn ld-primary" disabled={busy||!preview.eligible} onClick={()=>upload(file,true)}>{busy?'Importing…':`Import ${preview.eligible} rows`}</button><small>Preview shows up to 8 rows.</small></div></>}{report&&<p><strong>{report.ready} drafts saved</strong> · {report.created} new authors · {report.skipped} skipped</p>}{!!(preview||report)?.issues?.length&&<details><summary>View skipped rows ({(preview||report).issues.length})</summary><ul>{(preview||report).issues.slice(0,20).map((r,i)=><li key={i}>Row {r.row}: {r.name||'Unnamed'} · {r.reason}</li>)}</ul><button className="ld-btn" onClick={()=>issuesCSV(preview||report)}>Download full report</button></details>}</section>}
 <div className={'ld-workspace '+(mobile&&selected?'ld-mobile-compose':'')}><aside className="ld-queue"><div className="ld-queue-heading"><h2>Conversations</h2><button className="ld-refresh" aria-label="Refresh messages" disabled={loading} onClick={load}>↻</button></div><label className="ld-search"><span>⌕</span><input aria-label="Search messages" placeholder="Find an author, email or subject" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></label><div className="ld-filters">{['ready','sent','replied','all'].map(s=><button key={s} className={filter===s?'active':''} onClick={()=>{setFilter(s);setOffset(0)}}>{s==='ready'?'To send':s[0].toUpperCase()+s.slice(1)}</button>)}</div><div className="ld-list" aria-busy={loading}>{loading?<div className="ld-empty">Loading conversations…</div>:!items.length?<div className="ld-empty"><span>✉</span><h3>{search?'No matches':'Your next conversation starts here'}</h3><p>{search?'Try another name or subject.':'Upload an author workbook with their first messages.'}</p><button className="ld-btn" disabled={dirty||busy} onClick={()=>input.current.click()}>Upload workbook</button></div>:items.map(m=><button key={m.id} className={'ld-contact '+(selected?.id===m.id?'selected':'')} onClick={()=>choose(m)}><span className="ld-avatar">{m.author_name.split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><span className="ld-contact-text"><strong>{m.author_name}</strong><small>{m.subject}</small><span className="ld-contact-meta">{m.author_country||'Author'} <em className={'ld-state '+state(m)}>{state(m)==='ready'?'To send':state(m)}</em></span></span></button>)}</div><footer className="ld-pagination"><button disabled={!offset||loading} onClick={()=>setOffset(v=>Math.max(0,v-100))}>← Previous</button><span>Page {offset/100+1}</span><button disabled={items.length<100||loading} onClick={()=>setOffset(v=>v+100)}>Next →</button></footer></aside>
 <article className="ld-editor">{!selected||!draft?<div className="ld-welcome"><div className="ld-letter-icon">✎</div><p className="eyebrow">A SPACE FOR BETTER OUTREACH</p><h2>One author.<br/>One personal message.</h2><p>Select an author to review their research,<br/>refine your message and start a conversation.</p><div className="ld-empty-guide"><span>✓ Keep the exact message from your workbook</span><span>✓ Edit both language versions</span><span>✓ Track sent emails and replies</span></div></div>:<><div className="ld-editor-header"><button className="ld-back" onClick={()=>setMobile(false)}>← Authors</button><div><span className="eyebrow">YOUR CONVERSATION WITH</span><h2>{selected.author_name}</h2><p>{[selected.author_country,selected.author_genre].filter(Boolean).join(' · ')}</p></div><span className={'ld-state '+state(selected)}>{state(selected)==='ready'?'Draft':state(selected)}</span></div>
 {(selected.author_books||selected.author_website)&&<div className="ld-context"><span>▤</span><div><strong>From your author research</strong>{selected.author_books&&<p>{selected.author_books}</p>}{safeURL(selected.author_website)&&<a href={safeURL(selected.author_website)} target="_blank" rel="noreferrer">Author website ↗</a>}{safeURL(selected.email_source_url)&&<a href={safeURL(selected.email_source_url)} target="_blank" rel="noreferrer">Email source ↗</a>}</div></div>}
 <div className="ld-compose"><label className="ld-line"><span>To</span><input type="email" disabled={locked||busy} value={draft.recipient} onChange={e=>edit('recipient',e.target.value)}/></label><label className="ld-line"><span>Subject</span><input disabled={locked||busy} maxLength={400} value={draft.subject} onChange={e=>edit('subject',e.target.value)}/></label><div className="ld-language"><div>{[['body','Primary message'],['body_english','English version']].map(([k,l])=><button key={k} className={lang===k?'active':''} onClick={()=>{setLang(k);setReviewed(false)}}>{l}</button>)}</div><span>{body.length.toLocaleString()} characters</span></div><textarea aria-label={lang==='body'?'Primary message':'English version'} className="ld-body" disabled={locked||busy} value={body} maxLength={30000} placeholder="Add the exact message you want this author to receive…" onChange={e=>edit(lang,e.target.value)}/>{!locked&&<label className="ld-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I have reviewed the recipient, message and facts.</label>}<div className="ld-actions">{!locked&&<><button className="ld-btn ld-primary" disabled={!canSend} onClick={()=>compose('gmail')}>Open in Gmail ↗</button><button className="ld-btn" disabled={!canSend} onClick={()=>compose('email')}>Email app ↗</button></>}<button className="ld-btn" disabled={busy||!dirty} onClick={save}>{busy?'Working…':locked?'Save notes':'Save draft'}</button><button className="ld-btn" onClick={async()=>{try{await navigator.clipboard.writeText(body);setNotice('Message copied.')}catch{setError('Copy unavailable. Select and copy the message manually.')}}}>Copy</button></div><p className="ld-help">{dirty?'You have unsaved changes. ':''}{locked?'Sent message content is preserved. You can update conversation notes.':'Opening your email app does not mark the message as sent.'}</p>
 {gmail.connected&&!locked&&<details className="ld-direct"><summary>Send directly with a connected Gmail account</summary><div className="ld-actions"><select aria-label="Sender account" value={sender} onChange={e=>setSender(e.target.value)}><option value="">Default connected account</option>{gmail.accounts.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select><button className="ld-btn" disabled={!canSend} onClick={send}>Send this email</button></div></details>}
 <div className="ld-tracking"><h3>Conversation</h3><div className="ld-actions">{!locked&&<button className="ld-btn" disabled={busy||!draft.recipient||!draft.body.trim()} onClick={()=>mark('sent')}>✓ I sent this email</button>}{selected.reply_status!=='replied'&&<button className="ld-btn" disabled={busy} onClick={()=>mark('replied')}>↩ Mark replied</button>}{selected.sent_at&&<span>Sent {new Date(selected.sent_at).toLocaleDateString()}</span>}</div><label htmlFor="ld-notes">Reply and next steps</label><textarea id="ld-notes" disabled={busy} value={draft.reply_notes} maxLength={30000} onChange={e=>edit('reply_notes',e.target.value)} placeholder="Paste their reply, record a follow-up or note your next step…"/>{selected.author_bio&&<details><summary>Author biography</summary><p>{selected.author_bio}</p></details>}</div></div></>}</article></div></section>
}
